<?php
/**
 * 閲覧側のヘッター
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $siteInfos  サイト情報       
 * @author      suzuki-mar
 */
 
/*
if (empty($this->pageTitle)) {
    $this->headTitle($this->escape($this->siteInfos['name']));
} else {
    $this->headTitle($this->pageTitle)->setSeparator(' | ')->headTitle($this->escape($this->siteInfos['name']));
}

*/

?>
<?php //echo $this->doctype() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-style-type" content="text/css" />
        <meta http-equiv="content-script-type" content="text/javascript" />

        <meta name="author" content="" />
        <meta name="copyright" content="<?php //echo $this->escape($this->siteInfos['name']) ?>" />
        <meta name="generator" content="SetucoCMS <?php //echo APPLICATION_VERSION ?>" />
        <meta http-equiv="imagetoolbar" content="no" />

        <meta name="description" content="<?php //echo $this->escape($this->siteInfos['comment']) ?>" />
        <meta name="keywords" content="<?php //echo $this->escape($this->siteInfos['keyword']) ?>" />

        <link rel="start" href="<?php //echo $this->escape($this->siteInfos['url']) ?>" title="このサイトのトップページ" />

        <link rel="stylesheet" type="text/css" href="../public/css/style.css" media="screen" />

        <?php //echo $this->headTitle() . "\n" ?>
    </head>
    <body id="errorPage">

        <!-- wrapper START -->
        <div id="wrapper">

            <!-- header START -->
            <div id="header_innerL">

<div id="header_innerR"> 
    <div id="header_inner"> 

        <div id="discript"> 
            <h1><a href="<?php //echo $baseUrl('') ?>" tabindex="1">SetucoCMS</a></h1>
        </div> 
 
    </div> 
 </div> 
            </div>

            <div id="content">
                <div id="mainContent">
            <div class="entry">
