<?php
/**
 * 閲覧側のヘッター
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $siteInfos  サイト情報       
 * @author      suzuki-mar
 */
 
/*
if (empty($this->pageTitle)) {
    $this->headTitle($this->escape($this->siteInfos['name']));
} else {
    $this->headTitle($this->pageTitle)->setSeparator(' | ')->headTitle($this->escape($this->siteInfos['name']));
}

*/

?>


            <!-- header START -->

<div id="header_innerR"> 
    <div id="header_inner"> 

        <div id="discript"> 
            <h1><a href="<?php //echo $baseUrl('') ?>" tabindex="1">SetucoCMS</a></h1>
        </div> 
 
    </div> 
 </div> 
            