<?php // TODO  Zend_Navigation 使う？ ?>

<!-- gNav START -->
<ul id="gNav">

    <li><a href="<?php echo $this->baseUrl('') ?>index.php" title="管理画面のトップに戻ります"><img src="<?php echo $this->baseUrl('') ?>images/btn_menu_top.jpg" alt="トップ" width="150" height="30" /></a></li>

    <li>
        <dl>
            <dt><img src="<?php echo $this->baseUrl('') ?>images/h_menu_directory.jpg" alt="サイト構造" width="150" height="30" /></dt>
                <dd<?php if ($active == 'directory') echo ' id="active"'; ?>><a href="<?php echo $this->baseUrl('') ?>directory/index.php">カテゴリー・ページの一覧</a></dd>
        </dl>
    </li>

    <li>
        <dl>
            <dt><img src="<?php echo $this->baseUrl('') ?>images/h_menu_category.jpg" alt="カテゴリー" width="150" height="30" /></dt>
                <dd<?php if ($active == 'category') echo ' id="active"'; ?>><a href="<?php echo $this->baseUrl('') ?>category/index.php">追加・編集・削除</a></dd>
        </dl>
    </li>

    <li>
        <dl>
            <dt><img src="<?php echo $this->baseUrl('') ?>images/h_menu_page.jpg" alt="ページ" width="150" height="30" /></dt>
                <dd<?php if ($active == 'pageContribution') echo ' id="active"'; ?>><a href="<?php echo $this->baseUrl('') ?>page/contribution/index.php">新規作成</a></dd>
                <dd<?php if ($active == 'page') echo ' id="active"'; ?>><a href="<?php echo $this->baseUrl('') ?>page/index.php">編集・削除</a></dd>
        </dl>
    </li>

    <li>
        <dl>
            <dt><img src="<?php echo $this->baseUrl('') ?>images/h_menu_tag.jpg" alt="タグ" width="150" height="30" /></dt>
                <dd<?php if ($active == 'tag') echo ' id="active"'; ?>><a href="<?php echo $this->baseUrl('') ?>tag/index.php">追加・編集・削除</a></dd>
        </dl>
    </li>
    <li>
        <dl>
            <dt><img src="<?php echo $this->baseUrl('') ?>images/h_menu_file.jpg" alt="ファイル" width="150" height="30" /></dt>
                <dd<?php if ($active == 'file') echo ' id="active"'; ?>><a href="<?php echo $this->baseUrl('') ?>file/index.php">追加・編集・削除</a></dd>
        </dl>
    </li>

    <li>
        <dl>
            <dt><img src="<?php echo $this->baseUrl('') ?>images/h_menu_site.jpg" alt="サイト全般" width="150" height="30" /></dt>
                <dd<?php if ($active == 'site') echo ' id="active"'; ?>><a href="<?php echo $this->baseUrl('') ?>site/index.php">サイト情報の編集</a></dd>
        </dl>
    </li>

</ul>
<!-- gNav END -->
