<?php
/**
 * カテゴリー・ページの一覧画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Directory
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      Zend_Navigation $directory サイト構造の情報
 * @author     charlesvineyard
 */
?>

<?php $this->headStyle()->captureStart() ?>
.category ul {
    display: none;
}
<?php $this->headStyle()->captureEnd() ?>

<?php $this->headScript()->captureStart() ?>
dojo.require('dojo.NodeList-traverse');

function openCategory(switcher) {
    dojo.query(switcher.parentNode).next().style('display', 'block');
    dojo.query(switcher).children().at(0).attr('src', '<?php echo $this->baseUrl('/images/admin/directory/icn_category_open.gif') ?>');
    dojo.query(switcher).attr('onclick', 'closeCategory(this)');
}
function closeCategory(switcher) {
    dojo.query(switcher.parentNode).next().style('display', 'none');
    dojo.query(switcher).children().at(0).attr('src', '<?php echo $this->baseUrl('/images/admin/directory/icn_category_close.gif') ?>');
    dojo.query(switcher).attr('onclick', 'openCategory(this)');
}
<?php $this->headScript()->captureEnd() ?>

<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>サイト構造（カテゴリー・ページの一覧）</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">
    <div class="topichAreaL">
        <div class="topichAreaR">
            <div class="topichArea">
                <h3>
                    <img src="<?php echo $this->baseUrl('/images/admin/directory/h_directory.jpg') ?>" width="283" height="18" alt="サイト構造（カテゴリー・ページの一覧）" />
                </h3>
            </div>
        </div>
    </div>
    <ul id="directory">
    <?php
    foreach ($this->directory as $category):
        $pageCount = $category->count();
    ?>
        <li class="category<?php echo $this->cycle(array(' check', ''))->next() ?>">
            <?php if ($pageCount === 0): // カテゴリーの中身が空のとき ?>
            <div>
                <p class="folder">
                    <img src="<?php echo $this->baseUrl('/images/admin/directory/icn_category_noChild.gif') ?>" width="36" height="19" alt="カテゴリー" /><?php echo $category->getLabel() ?>
                </p>
                <p>
                    <img src="<?php echo $this->baseUrl('/images/admin/directory/icn_page.gif') ?>" width="11" height="12" alt="このカテゴリーに含まれるページ" /><?php echo $pageCount ?>
                </p>
            </div>
            <?php else: // カテゴリーの中身があるとき ?>
            <div>
                <p class="folder" onclick="openCategory(this)">
                    <img src="<?php echo $this->baseUrl('/images/admin/directory/icn_category_close.gif') ?>" width="36" height="19" alt="カテゴリーを開く" /><?php echo $category->getLabel() ?>
                </p>
                <p>
                    <a href="<?php echo $category->getHref() ?>">
                        <img src="<?php echo $this->baseUrl('/images/admin/directory/icn_page.gif') ?>" width="11" height="12" alt="このカテゴリーに含まれるページ" /><?php echo $pageCount ?>
                    </a>
                </p>
            </div>
            <ul>
            <?php
            $i = 0;
            foreach ($category as $page):
                $i++;
            ?>
                <li class="page<?php echo ($i === $pageCount) ? ' lastChild' : '' ?>">
                    <div>
                        <p>
                            <a href="<?php echo $page->getViewHref() ?>" target="_blank">
                                <img src="<?php echo $this->baseUrl('/images/admin/directory/icn_check.gif') ?>" width="18" height="15" alt="ページを確認" /><?php echo $page->getLabel() ?>
                            </a>
                        </p>
                        <p>
                            <a href="<?php echo $page->getEditHref() ?>">
                                <img src="<?php echo $this->baseUrl('/images/admin/directory/icn_edit.gif') ?>" width="17" height="17" alt="編集" />
                            </a>
                        </p>
                    </div>
                </li>
            <?php endforeach ?>
            </ul>
            <?php endif ?>
        </li>
    <?php endforeach ?>
    </ul>
</div>
<!-- section END -->
