<?php
/**
 * 更新目標の編集画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Index
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      string      $flashMessage フラッシュメッセージ
 * @param      Setuco_Form $goalForm     更新目標を編集するフォーム
 * @author     charlesvineyard
 */
?>
<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>更新目標の編集</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">
    <div class="hAreaL">
        <div class="hAreaR">
            <div class="hArea">
                <h3>
                    <img src="<?php echo $this->baseUrl('/images/admin/index/h_goal.jpg') ?>" width="107" height="18" alt="更新目標の編集" />
                </h3>
            </div>
        </div>
    </div>

    <?php if ($this->goalForm->isErrors()): ?>
        <div id="messageArea">
        <?php foreach ($this->goalForm->getMessages() as $elementName => $messages): ?>
            <?php if (!is_array($messages)):?>
            <p><?php echo $messages ?></p>
            <?php else: ?>
                <?php foreach ($messages as $message):?>
            <p><?php echo $message ?></p>
                <?php endforeach ?>
            <?php endif ?>
        <?php endforeach ?>
            <p>
                <a href="javascript:void(0)" onclick="hideFlashMessage()">OK</a>
            </p>
        </div>
    <?php endif ?>

    <?php echo $this->partial('action-message.phtml', array('flashMessages' => $this->flashMessages)); ?>

    <form id="<?php echo $this->goalForm->getId() ?>" enctype="application/x-www-form-urlencoded" method="<?php echo $this->goalForm->getMethod() ?>" action="<?php echo $this->goalForm->getAction() ?>">
        <dl class="editArea">
            <?php echo $this->goalForm->getElement('goal') . "\n" ?>
        </dl>
        <?php echo $this->goalForm->getElement('submit') . "\n" ?>
    </form>
</div>
<!-- section END -->
