<!-- topicPath START --> 
<div id="topicPath"> 
    <p><a href="../index.php">トップ</a><img src="../images/topicPath.gif" width="6" height="11" alt="の中の" /></p> 
    <p>更新目標の編集</p> 
</div> 
<!-- topicpath END --> 

<!-- section START --> 
<div class="section"> 

    <div class="topichAreaL"> 

        <div class="topichAreaR"> 

            <div class="topichArea"> 

                <h3><img src="<?php echo $this->baseUrl('/images/h_goal.jpg') ?>" width="109" height="18" alt="更新目標の編集" /></h3> 

            </div> 

        </div> 

    </div> 

    <?php if (count($this->flashMessage)): ?>
        <div id="messageArea">
            <p><?php echo $this->flashMessage ?></p>
            <p><a href="javascript:void(0)" onclick="hideFlashMessage()">OK</a></p>
        </div>
    <?php endif; ?>
    
    <?php echo $this->goalForm ?> 

</div> 
<!-- section END --> 
