 <!-- topicPath START --> 
                <div id="topicPath"> 
                    <p><a href="../index.php">トップ</a><img src="../images/topicPath.gif" width="6" height="11" alt="の中の" /></p> 
                    <p>更新目標の編集</p> 
                </div> 
                <!-- topicpath END --> 
 
                <!-- section START --> 
                <div class="section"> 
 
                    <div id="topichAreaL"> 
 
                        <div id="topichAreaR"> 
 
                            <div id="topichArea"> 
 
                                <h3><img src="../images/h_goal.jpg" width="109" height="18" alt="更新目標の編集" /></h3> 
 
                            </div> 
 
                        </div> 
 
                    </div> 
 
                    
                    <form action="edit.php" method="post"> 
 
                        <dl class="editArea"> 
 
                            <dt><label for="goal_span">更新間隔</label></dt> 
                                <dd><input type="text" id="goal_span" name="goal_span" value='24' onblur="if(this.value == '') { this.value='24'; }" />日置き</dd> 
 
                            <dt><label for="goal_month">一ヶ月の更新数</label></dt> 
                                <dd><input type="text" id="goal_month" name="goal_month" value='-10' onblur="if(this.value == '') { this.value='-10'; }" />ページ</dd> 
 
                        </dl> 
 
                        <p class="editAreaP"><input type="submit" id="sub" name="sub" value="更新目標を変更" /></p> 
 
                    </form> 
 
                </div> 
                <!-- section END --> 
