<style>
#ambitionForm {
    display: none;
}
</style>
<script>
function showAmbitionForm() {
    dojo.style('ambitionView', {display: 'none'});   
    dojo.style('ambitionForm', {display: 'inline'});
    dojo.query('#ambitionForm input[name$=ambition]')[0].value =
            dojo.byId('ambitionValue').innerHTML;
}
function hideAmbitionForm() {
    dojo.style('ambitionForm', {display: 'none'});   
    dojo.style('ambitionView', {display: 'inline'});
}
</script>

<!-- section"野望" START -->
<div class="section">

        <dl id="designs">
            <dt>野望</dt>
            <dd>
                <span id="ambitionView">
                    <em>「<span id="ambitionValue"><?php echo $this->ambition ?></span>」</em>
                    <a href="javascript:void(0)" onclick="showAmbitionForm()">
                        <img src="<?php echo $this->baseUrl('/images/btn_edit.gif') ?>" alt="野望を変更する" width="21" height="21" />
                    </a>
                </span>
                <?php echo $this->ambitionForm ?>
            </dd>
        </dl>
    </form>
</div>
<!-- section"野望" END -->

<!-- section"現在の状況" START -->
<div id="topicSection">

    <div class="topichAreaL">

        <div class="topichAreaR">

            <div class="topichArea">

                <h3><img src="images/h_nowData.gif" alt="現在の状況" width="110" height="22" /></h3>

                <p><a href="<?php echo $this->baseUrl('admin/index/form-goal') ?>">更新目標の編集</a></p>

            </div>

        </div>

    </div>

    <dl class="check">

        <dt>更新状況</dt>
            <dd>良い！</dd>

    </dl>


    <dl class="straight">

        <dt>最終更新日</dt>
            <dd>2010/08/08（0日経過）</dd>

    </dl>

    <dl class="check">

        <dt>今月の作成数</dt>
            <dd>1ページ（目標からプラス11ページ！）</dd>

    </dl>

    <dl class="straight">

        <dt>総ページ数</dt>

            <dd>62ページ</dd>

    </dl>

    <dl class="check">

        <dt>経過日数</dt>
            <dd>113日目（2009/09/01開設）</dd>

    </dl>

</div>
<!-- section"現在の状況" END -->

<!-- section"最近作ったページ" START -->
<div class="section">

                    <div class="topichAreaL">

                        <div class="topichAreaR">

                            <div class="topichArea">

                                <h3 id="recentry"><img src="images/h_recentlyPage.jpg" alt="最近作ったページ" width="194" height="23" /></h3>

                                <p><a href="page/index.php">ページの一覧（編集・削除）へ</a></p>
                            </div>

                        </div>

                    </div>

    <dl class='contentsListK'>
        <dt class="pageDate">2010/08/08 20:26:00</dt>

        <dd class="pageTitle"><a href='page/edit/index.php?page_id=109'>くるくるくるくる</a></dd>

        <dt>カテゴリー</dt>
        <dd>link</dd>

        <dt>制作者</dt>
        <dd>admin</dd>

        <dt>公開状態</dt>

        <dd>公開</dd>

    </dl>
    <dl class='contentsListG'>
        <dt class="pageDate">2010/07/20 17:59:26</dt>

        <dd class="pageTitle"><a href='page/edit/index.php?page_id=107'>ええ</a></dd>

        <dt>カテゴリー</dt>

        <dd>未分類</dd>

        <dt>制作者</dt>
        <dd>admin</dd>

        <dt>公開状態</dt>
        <dd>公開</dd>

    </dl>
    <dl class='contentsListK'>
        <dt class="pageDate">2010/07/20 17:49:40</dt>

        <dd class="pageTitle"><a href='page/edit/index.php?page_id=106'>test</a></dd>

        <dt>カテゴリー</dt>
        <dd>未分類</dd>

        <dt>制作者</dt>
        <dd>admin</dd>

        <dt>公開状態</dt>
        <dd>下書き</dd>

    </dl>

    <dl class='contentsListG'>
        <dt class="pageDate">2010/07/06 10:27:11</dt>

        <dd class="pageTitle"><a href='page/edit/index.php?page_id=105'>キーワード</a></dd>

        <dt>カテゴリー</dt>
        <dd>未分類</dd>

        <dt>制作者</dt>

        <dd>admin</dd>

        <dt>公開状態</dt>
        <dd>公開</dd>

    </dl>
    <dl class='contentsListK'>
        <dt class="pageDate">2010/06/10 00:05:22</dt>

        <dd class="pageTitle"><a href='page/edit/index.php?page_id=104'>aaa</a></dd>

        <dt>カテゴリー</dt>
        <dd>contents</dd>

        <dt>制作者</dt>
        <dd>admin</dd>

        <dt>公開状態</dt>
        <dd>公開</dd>

    </dl>

</div>

<!-- section"最近作ったページ" END -->
