<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>サイト情報の編集</p>
</div>
<!-- topicpath END -->

    <!-- section START --> 
    <div class="section"> 
        <div class="topichAreaL"> 
            <div class="topichAreaR"> 
                <div class="topichArea"> 
                    <h3><img src="<?php echo $this->baseUrl('/images/admin/site/h_site.jpg') ?>" width="122" height="18" alt="サイト情報の編集" /></h3>
                </div> 
            </div> 
        </div> 

        <form action="/admin/site/update" method="post"> 

        <?php if (count($this->flashMessage)) : ?>
            <div id='messageArea'>
                <p><?php echo $this->flashMessage ?></p>
                <p><a href="javascript:void(0)" onclick="hideFlashMessage()">OK</a></p>
            </div>
        <?php endif; ?>

            <dl id="siteForm" class="editArea"> 

                <dt><label for="name">サイト名</label></dt> 
                <dd><input type="text" id="name" name="name" value="<?php echo $this->sites['name'];?>" onblur="if(this.value == '') { this.value='<?php echo $this->sites['name'];?>'; }" /><br /><span>サイト上に表示される名前です。</span></dd> 

                <dt><label for="url">サイトURL<br /><span>（リンク切れに注意）</span></label></dt> 
                <dd><input type="text" id="url" name="url" value="<?php echo $this->sites['url'];?>" onblur="if(this.value == '') { this.value='<?php echo $this->sites['url'];?>'; }" /><br /><span>サイトを表示するURLです。</span></dd> 

                <dt id="site_description_t"><label for="description">説明</label></dt> 
                <dd id="site_description_d"><textarea rows="2" id="comment" name="comment"><?php echo $this->sites['comment'];?></textarea><br /><span>サイトの説明です。サイトの概要を入力してください。</span></dd> 
<!--<dd><input type="text" id="comment" name="comment" value='' /></dd>--> 

                <dt><label for="keyword">キーワード<br /><span>（カンマ[&nbsp;,&nbsp;]で区切る）</span></label></dt> 
                <dd><input type="text" id="keyword" name="keyword" value="<?php echo $this->sites['keyword'];?>" /><br /><span>サイトのキーワードです。サイトに関連する単語を入力してください。</span></dd> 

            </dl> 

            <p class="editAreaP"><input type="submit" id="sub" name="sub" value="サイト情報を変更" /></p> 

        </form> 

    </div> 
    <!-- section END --> 
