<?php
/**
 * サイト情報更新画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Category
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      array            $sites   サイト情報データ
 * @param      array[option]    $flashMessages アクションの実行結果
 * @param      Setuco_Form      $errorForm エラーメッセージを表示するフォームクラス
 * @author     suzuki-mar
 */
?>

<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>サイト情報の編集</p>
</div>
<!-- topicpath END -->

    <!-- section START -->
    <div class="section">
        <div class="hAreaL">
            <div class="hAreaR">
                <div class="hArea">
                    <h3><img src="<?php echo $this->baseUrl('/images/admin/site/h_site.jpg') ?>" width="122" height="18" alt="サイト情報の編集" /></h3>
                </div>
            </div>
        </div>

        <?php echo $this->partial('action-message.phtml', array('flashMessages' => $this->flashMessages)) ?>
        <?php if (isset($this->errorForm)) {
                echo $this->partial('error-message.phtml', array('errorForm' => $this->errorForm));
        }  ?>




        <form action="<?php echo $this->baseUrl('/admin/site/update') ?>" method="post">

            <dl id="siteForm" class="editArea">

                <dt><label for="name"><span class="required">[必須]</span>サイト名</label></dt>
                <dd><input type="text" id="name" name="name" value="<?php echo $this->escape($this->sites['name']) ?>" onblur="if(this.value == '') { this.value='<?php echo $this->escape($this->sites['name']) ?>'; }" /><br /><span>サイト上に表示される名前です。</span></dd>

                <dt><label for="url"><span class="required">[必須]</span>サイトURL<br /><span class="attentionMessage">（リンク切れに注意）</span></label></dt>
                <dd><input type="text" id="url" name="url" value="<?php echo $this->escape($this->sites['url']) ?>" onblur="if(this.value == '') { this.value='<?php echo $this->escape($this->sites['url']) ?>'; }" /><br /><span>サイトを表示するURLです。</span></dd>

                <dt id="site_description_t"><label for="comment">説明</label></dt>
                <dd id="site_description_d"><textarea rows="2" cols="" id="comment" name="comment"><?php echo $this->escape($this->sites['comment']) ?></textarea><br /><span>サイトの説明です。サイトの概要を入力してください。</span></dd>
<!--<dd><input type="text" id="comment" name="comment" value='' /></dd>-->

                <dt><label for="keyword">キーワード<br /><span class="attentionMessage">（カンマ[&nbsp;,&nbsp;]で区切る）</span></label></dt>
                <dd><input type="text" id="keyword" name="keyword" value="<?php echo $this->escape($this->sites['keyword']) ?>" /><br /><span>サイトのキーワードです。サイトに関連する単語を入力してください。</span></dd>

            </dl>

            <p class="defaultOver"><input type="submit" id="sub" name="sub" value="サイト情報を変更" /></p>

        </form>

    </div>
    <!-- section END -->

