
<!-- section START -->
<div class="section">

    <div class="default">
      <h2>An error occurred</h2>
      <h3><?php echo $this->message ?></h3>

      <?php if (isset($this->exception)): ?>

      <h4>Exception information:</h4>
      <p>
          Message: <?php echo $this->exception->getMessage() ?>
      </p>

      <h4>Stack trace:</h4>
      <p><?php echo $this->exception->getTraceAsString() ?></p>

      <h4>Request Parameters:</h4>
      <p><?php echo var_export($this->requestParams, true) ?></p>
      <?php endif ?>
    </div>
</div>
<!-- section END -->
