<?php
/**
 * ヘッダーの画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Layout
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version    
 * @since      File available since Release 0.1.0
 * @param      string $siteName  サイト名
 * @param      string $siteUrl   サイトURL
 * @param      string $nickName  ログイン中のアカウントのニックネーム
 * @author     charlesvineyard
 */
?>
<div>
    <h1>
        <a href="<?php echo $this->baseUrl('/admin') ?>" title="管理画面のトップに戻ります">
            <img src="<?php echo $this->baseUrl('/images/header/logo.jpg') ?>" alt="せつこCMS"  width="152" height="39" />
        </a>
    </h1>
    <h2>
        <a href="<?php echo $this->siteUrl ?>" title="サイトのトップページを表示します" target="_blank">
            <span><?php echo $this->siteName ?></span>
            <img src="<?php echo $this->baseUrl('/images/header/btn_watchSite.jpg') ?>" alt="サイトを確認する" width="108" height="29" />
        </a>
    </h2>
</div>

<form action="<?php echo $this->baseUrl('/admin/login/logout') ?>" method="post">
    <ul>
        <li id="utilLogout">
            <input onmouseover="this.className='logoutOver'" onmouseout="this.className='logoutNormal'" type="submit" id="sub" name="sub" value="ログアウト" />
        </li>
        <li id="utilAccount">
            <span><?php echo $this->nickName ?></span>でログイン中
        </li>
    </ul>
</form>
