<?php
/**
 * ログイン画面のレイアウト
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Layout
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @author     charlesvineyard
 */
?>
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
                 ->appendHttpEquiv('content-script-type', 'text/jascript')
                 ->appendHttpEquiv('content-style-type', 'text/css')
                 ->appendName('author', 'ErinaMikami with SetucoCMS Project')
                 ->appendName('copyright', 'SetucoCMS')
                 ->appendHttpEquiv('imagetoolbar', 'no');
$this->headTitle('ログイン画面')->setSeparator(':')->headTitle('SetucoCMS');
$this->headLink()->prependStylesheet($this->baseUrl('css/base.css'));
$this->headScript()->prependFile($this->baseUrl('js/jquery-1.7.1.min.js'));
$this->headScript()->prependFile($this->baseUrl('js/admin.js'));
?>
<?php echo $this->doctype() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
    <head>
        <?php echo $this->headMeta() . "\n" ?>
        <?php echo $this->headTitle() . "\n" ?>
        <?php echo $this->dojo() . "\n" ?>
        <?php echo $this->headScript() . "\n" ?>
        <?php echo $this->headLink() . "\n" ?>
        <?php echo $this->headStyle() . "\n" ?>
    </head>
    <body id="loginBoad">

        <!-- container START -->
        <div id="container">
            <?php echo $this->layout()->content ?>
            <?php echo $this->render('footer.phtml') ?>
        </div>
        <!-- container END -->

    </body>
</html>
