<?php
/**
 * ログイン画面のレイアウト
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Layout
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @author     charlesvineyard
 */
?>
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')
                 ->appendHttpEquiv('content-script-type', 'text/jascript')
                 ->appendHttpEquiv('content-style-type', 'text/css')
                 ->appendName('author', 'ErinaMikami with SetucoCMS Project')
                 ->appendName('copyright', 'SetucoCMS')
                 ->appendHttpEquiv('imagetoolbar', 'no');
$this->headTitle('ログイン画面')->setSeparator(':')->headTitle('SetucoCMS');
$this->headLink()->prependStylesheet($this->baseUrl('css/base.css'));
$this->headScript()->prependFile($this->baseUrl('js/admin.js'));
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->dojo() ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
    </head>
    <body id="loginBoad">

        <!-- container START -->
        <div id="container">

            <?php echo $this->layout()->content ?>
            <?php echo $this->render('footer.phtml') ?>

        </div>
        <!-- container END -->

    </body>
</html>
