<!-- entry START -->
<div class="entry">

    <div class="entryHead">

        <h2>フリースペース</h2>

    </div>

    <div class="entryBody">

        <p><?php echo $this->freeSpace ?></p>

    </div>

</div>
<!-- entry END -->

<!-- entry START -->

<div class="entry">

    <div class="entryHead">

    <h2>新着ページ</h2>

    </div>

    <div class="entryBody">
        <ul>
            <?php foreach ($this->newPages as $value): ?>
            <li><a href='<?php echo $this->baseUrl("/page/show/id/{$value['id']}") ?>'><?php echo $value['title'] ?></a></li>
            <?php endforeach; ?>
        </ul>

    </div>

    <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>

</div>
<!-- entry END -->

