<?php
/**
 * 閲覧側のTOPページ
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Script_Index
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $newPages     記事一覧ページに表示させるページデータ       
 * @author      suzuki-mar
 */
?>


<!-- entry START -->
<div class="entry">

    <div class="entryHead">

        <h2>フリースペース</h2>

    </div>

    <div class="entryBody">

        <p>
        テスト運用中。フリーエリアです。
        </p>

    </div>

</div>
<!-- entry END -->

<!-- entry START -->

<div class="entry">

    <div class="entryHead">

    <h2>新着ページ</h2>

    </div>

    <div class="entryBody">
        <?php if($this->newPages !== false): //記事が公開されている場合のみ表示する ?>
        <ul>
            <li>
                <?php foreach ($this->newPages as $value): ?>
                <a href='<?php echo $this->baseUrl("/page/show/id/{$value['id']}") ?>'><?php echo $value['title'] ?></a>
                <?php endforeach; ?>
            </li>
        </ul>        
        
        <?php else: //記事が公開されていない場合 ?>
        <p>記事が公開されていません</p>
        <?php endif; ?>
             

    </div>
    <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>
    <?php echo $this->paginator; ?>


</div>
<!-- entry END -->

