<!-- entry START -->
<div class="entry">

    <div class="entryHead">

        <h2>フリースペース</h2>

    </div>

    <div class="entryBody">

        <p>テスト運用中。フリーエリアです。</p>

    </div>

</div>
<!-- entry END -->

<!-- entry START -->

<div class="entry">

    <div class="entryHead">

    <h2>新着ページ</h2>

    </div>

    <div class="entryBody">

        <ul>
            <li><a href='page.php?page_id=109'>くるくるくるくる</a></li>
            <li><a href='page.php?page_id=107'>ええ</a></li>
            <li><a href='page.php?page_id=105'>キーワード</a></li>
            <li><a href='page.php?page_id=104'>aaa</a></li>
            <li><a href='page.php?page_id=103'>てすと</a></li>
            <li><a href='page.php?page_id=100'>なんとなく更新してみる</a></li>
            <li><a href='page.php?page_id=99'>校長賞とりました。</a></li>
            <li><a href='page.php?page_id=98'>制作展が(´ω｀)</a></li>
            <li><a href='page.php?page_id=97'>テスト勉強の気分転換にきました</a></li>
            <li><a href='page.php?page_id=96'>何がおきた</a></li>                            
        </ul>

    </div>

    <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>

</div>
<!-- entry END -->

