<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-style-type" content="text/css" />
        <meta http-equiv="content-script-type" content="text/javascript" />

        <link rel="stylesheet" type="text/css" href="/css/style.css" media="screen" />

        <title>ページが見つかりません(404 Not Found)｜サイト名</title>

    </head>
    <body id="errorPage">

        <!-- wrapper START -->
        <div id="wrapper">

            <!-- header START -->
            <div id="header_innerL">
                <div id="header_innerR"> 
                    <div id="header_inner"> 
                        <div id="discript"> 
                            <h1><a href="/" tabindex="1">サイト名</a></h1>
                        </div>
                    </div>
                 </div>
            </div>

            <!-- header END -->

            <!-- content START -->
            <div id="content">

                <!-- mainContent START -->
                <div id="mainContent">

                    <!-- entry START -->
                    <div class="entry">

                        <div class="entryHead">

                            <h2><span>ページが見つかりません(404 Not Found)</span></h2>
                        </div>

                        <div class="entryBody">
                            <p>アクセスされたページは、移動または削除された可能性があります。<br />HOMEより目的のページをお探しください。</p>
                            <p><a href="#">HOMEへ戻る</a></p>
                        </div>

                    </div>
                    <!-- entry END -->

            </div>
            <!-- content END -->

            <p id='copyright'>Copyright &copy; 解説年 サイト名 AllRight reserved.</p>

        </div>
        <!-- container END -->

    </body>

</html>