<!-- topicPath START --> 
<div id="topicPath"> 
<p><a href="../index.php">トップ</a><img src="<?php echo $this->baseUrl('/images/topicPath.gif') ?>" width="6" height="11" alt="の中の" /></p> 
    <p>ページの編集・削除</p> 
</div> 
<!-- topicpath END --> 

<!-- section START --> 
<div class="section"> 

    <div class="topichAreaL"> 

        <div class="topichAreaR"> 

            <div class="topichArea"> 

                <h3><img src="<?php echo $this->baseUrl('/images/h_pageAll.jpg'); ?>" width="135" height="18" alt="ページの編集・削除" /></h3> 

            </div> 

        </div> 

    </div> 

    
    <form action="#" method="post"> 

        <div id="pageSearch"> 

            <dl class="over">
                <dt><label for="keyword">キーワード</label></dt> 
                    <dd><input id="keyword" name="keyword" type="text" class="defaultInput" /></dd> 
                    <dd class="clear"><input id="oora1" type="radio" name="oora" checked="checked" /><label for="oora1">OR</label></dd> 
                    <dd><input id="oora2" type="radio" name="oora" /><label for="oora2">AND</label></dd> 
                    <dd><input id="qora1" type="checkbox" name="qora" /><label for="qora1">タイトル</label></dd> 
                    <dd><input id="qora2" type="checkbox" name="qora" /><label for="qora2">本文</label></dd> 
                    <dd><input id="qora3" type="checkbox" name="qora" /><label for="qora3">概要</label></dd> 
                    <dd><input id="qora4" type="checkbox" name="qora" /><label for="qora4">キーワード</label></dd> 
                    <dd><input id="qora5" type="checkbox" name="qora" /><label for="qora5">タグ</label></dd> 
            </dl>
            <dl class="under">
                <dt>カテゴリー</dt>
                    <dd><select>
                        <option value="0"selected="selected">--指定なし--</option>
                        <option value="1">カテゴリー1</option>
                        <option value="2">カテゴリー2</option>
                        <option value="3">カテゴリー3</option>
                        <option value="4">カテゴリー4</option>
                    </select></dd>

                <dt>制作者</dt>
                    <dd><select>
                        <option value="0"selected="selected">--指定なし--</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select></dd>

                <dt>公開状態</dt>
                    <dd><select>
                    <option value="0"selected="selected">--指定なし--</option>
                    <option value="1">公開</option>
                    <option value="2">非公開</option>
                    </select></dd>
            </dl>
                <p><input type="button" value="検索" /></p> 
        </div> 

    </form> 

    <form action="page_edit.php" method="post" name="form"> 

        <table summary="ページ一覧の表です。タイトルのリンクと編集ボタンから、ページの編集ができます。削除ボタンから削除ができます。" cellpadding="0" cellspacing="0"> 
            <colgroup>
                <col width="7%" />
                <col width="35%" />
                <col width="16%" />
                <col width="10%" />
                <col width="15%" />
                <col width="10%" />
                <col width="7%" />
            </colgroup>
            <thead> 
                <tr> 
                    <th scope="col" id="tableFirst">表示</th> 
                    <th scope="col">タイトル<a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" /></a><a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" /></a></th> 
                    <th scope="col">制作日<a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" /></a><a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" /></a></th> 
                    <th scope="col">制作者</th> 
                    <th scope="col">カテゴリー</th> 
                    <th scope="col">状態</th> 
                    <th scope="col">削除</th> 
                </tr> 
            </thead> 

            <tbody> 

                <tr> 
                <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=109' target='_blank'><img src="<?php echo $this->baseUrl('/images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=109'>くるくるくるくる</a></td> 
                        <td>2010/08/08</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=109&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19' selected='selected'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=109'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

<td><a href='#' onclick='flg(109);'><img src="<?php echo $this->baseUrl('images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr class='checkG'> 
                    <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=107' target='_blank'><img src="<?php echo $this->baseUrl('../images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=107'>ええ</a></td> 
                        <td>2010/07/20</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=107&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=107'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

<td><a href='#' onclick='flg(107);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr> 
                        <td><img src="<?php echo $this->baseUrl('/images/btn_check_no.png'); ?>" alt='下書きは表示できません' width='27' height='27' /></td> 
                        <td><a href='edit/index.php?page_id=106'>test</a></td> 
                        <td>2010/07/20</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=106&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=106'"><option value='0' selected>下書き</option> 
<option value='1'>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(106);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr class='checkG'> 
                        <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=105' target='_blank'><img src="<?php echo $this->baseUrl('/images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=105'>キーワード</a></td> 
                        <td>2010/07/06</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=105&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=105'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(105);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr> 
                        <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=104' target='_blank'><img src="<?php echo $this->baseUrl('/images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=104'>aaa</a></td> 
                        <td>2010/06/10</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=104&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12' selected='selected'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=104'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(104);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr class='checkG'> 
                        <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=103' target='_blank'><img src="<?php echo $this->baseUrl('/images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=103'>てすと</a></td> 
                        <td>2010/06/09</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=103&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=103'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(103);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr> 
                        <td><img src="<?php echo $this->baseUrl('/images/btn_check_no.png'); ?>" alt='下書きは表示できません' width='27' height='27' /></td> 
                        <td><a href='edit/index.php?page_id=101'>眠い</a></td> 
                        <td>2010/05/04</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=101&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=101'"><option value='0' selected>下書き</option> 
<option value='1'>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(101);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr class='checkG'> 
                        <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=100' target='_blank'><img src="<?php echo $this->baseUrl('/images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=100'>なんとなく更新してみる</a></td> 
                        <td>2010/02/24</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=100&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=100'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(100);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr> 
                        <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=99' target='_blank'><img src="<?php echo $this->baseUrl('/images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=99'>校長賞とりました。</a></td> 
                        <td>2010/02/13</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=99&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=99'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(99);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    <tr class='checkG'> 
                        <td><a href='http://design1.chu.jp/testsetuco/penguin//page.php?page_id=98' target='_blank'><img src="<?php echo $this->baseUrl('/images/btn_check.png'); ?>" alt='表示' width='27' height='27' /></a></td> 
                        <td><a href='edit/index.php?page_id=98'>制作展が(´ω｀)</a></td> 
                        <td>2010/02/12</td> 
                        <td>admin</td> 
                        <td><select id="not_cat" name="not_cat"
                            onchange="location.href='index.php?cat_edit=98&selected=' + (this.options[this.selectedIndex].value);"

                        ><option value='32'>about</option><option value='12'>contents</option><option value='19'>link</option><option value='42'>report</option><option value='46'>test</option><option value='49'>新規カテゴリー</option><option value='0' selected='selected'>未分類</option></select></td> 
                        <td><select id="not_this" name="not_this"onchange="location.href='index.php?state_edit=98'"><option value='0'>下書き</option> 
<option value='1' selected>公開</option> 
</select></td> 
                        

                                                                <td><a href='#' onclick='flg(98);'><img src="<?php echo $this->baseUrl('/images/btn_delete.png'); ?>" alt='削除' width='27' height='27' /></a></td> 
                    </tr> 

                    
            </tbody> 

        </table> 

    </form> 

    <div id="pageNav"> 
        <ul> 
            <li><a href="#">前へ</a></li> 
            <li class="navNumber"><a href="#">1</a></li> 
            <li class="navNumber current"><a href="#">2</a></li> 
            <li class="navNumber"><a href="#">3</a></li> 
            <li class="navNumber"><a href="#">4</a></li> 
            <li class="navNumber"><a href="#">5</a></li> 
            <li><a href="#">次へ</a></li> 
        </ul> 
    </div> 

</div> 
<!-- section END --> 
