<?php
/**
 * ページの編集・削除画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Page
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param
 * @author     charlesvineyard
 */
?>
<?php $this->headStyle()->captureStart() ?>
#status_edit {
    display: none;
}
#category_edit {
    display: none;
}
<?php $this->headStyle()->captureEnd() ?>
<?php $this->headScript()->captureStart() ?>
dojo.require('dojo.NodeList-traverse');
dojo.require('dojo.NodeList-html');

function showPageElementEdit(switcher) {
    dojo.query(switcher).parent().next().style('display', 'inline');
    defaultHtml = switcher.innerHTML;
}
function hidePageElementEdit(switcher) {
    dojo.query(switcher).parent().prev().children().at(0).html(defaultHtml);
    dojo.query(switcher).parent().style('display', 'none');
}
function confirmRedirect(url){
    if (confirm("本当に削除してよろしいですか？")) {
        location.href = url;
    }
}
<?php $this->headScript()->captureEnd() ?>

<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>ページの編集・削除</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">
    <div class="topichAreaL">
        <div class="topichAreaR">
            <div class="topichArea">
                <h3><img src="<?php echo $this->baseUrl('/images/admin/page/h_pageAll.jpg'); ?>" width="135" height="18" alt="ページの編集・削除" /></h3>
            </div>
        </div>
    </div>
    <?php if (count($this->flashMessages)): ?>
        <div id="messageArea">
        <?php foreach ($this->flashMessages as $flashMessage): ?>
            <p><?php echo $flashMessage ?></p>
        <?php endforeach ?>
            <p>
                <a href="javascript:void(0)" onclick="hideFlashMessage()">OK</a>
            </p>
        </div>
    <?php endif ?>

    <form action="#" method="post">
        <div id="pageSearch">
            <dl class="over">
                <dt><label for="keyword">キーワード</label></dt>
                    <dd><input id="keyword" name="keyword" type="text" class="defaultInput" /></dd>
                    <dd class="clear"><input id="oora1" type="radio" name="oora" checked="checked" /><label for="oora1">OR</label></dd>
                    <dd><input id="oora2" type="radio" name="oora" /><label for="oora2">AND</label></dd>
                    <dd><input id="qora1" type="checkbox" name="qora" /><label for="qora1">タイトル</label></dd>
                    <dd><input id="qora2" type="checkbox" name="qora" /><label for="qora2">本文</label></dd>
                    <dd><input id="qora3" type="checkbox" name="qora" /><label for="qora3">概要</label></dd>
                    <dd><input id="qora4" type="checkbox" name="qora" /><label for="qora4">キーワード</label></dd>
                    <dd><input id="qora5" type="checkbox" name="qora" /><label for="qora5">タグ</label></dd>
            </dl>
            <dl class="under">
                <dt>カテゴリー</dt>
                    <dd><select>
                        <option value="0" selected="selected">--指定なし--</option>
                        <option value="1">カテゴリー1</option>
                        <option value="2">カテゴリー2</option>
                        <option value="3">カテゴリー3</option>
                        <option value="4">カテゴリー4</option>
                    </select></dd>

                <dt>制作者</dt>
                    <dd><select>
                        <option value="0" selected="selected">--指定なし--</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select></dd>

                <dt>公開状態</dt>
                    <dd><select>
                    <option value="0" selected="selected">--指定なし--</option>
                    <option value="1">公開</option>
                    <option value="2">非公開</option>
                    </select></dd>
            </dl>
            <p><input type="button" value="検索" /></p>
        </div>
    </form>

    <table summary="ページ一覧の表です。タイトルのリンクと編集ボタンから、ページの編集ができます。削除ボタンから削除ができます。" cellpadding="0" cellspacing="0">
        <colgroup>
            <col width="7%" />
            <col width="35%" />
            <col width="16%" />
            <col width="10%" />
            <col width="15%" />
            <col width="10%" />
            <col width="7%" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col" id="tableFirst">表示</th>
                <th scope="col">タイトル名<a href="<?php echo $this->baseUrl('/admin/page/index/page/1/sort/title/order/desc') ?>">
                        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" />
                    </a>
                    <a href="<?php echo $this->baseUrl('/admin/page/index/page/1/sort/title/order/asc') ?>">
                        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" />
                    </a>
                </th>
                <th scope="col">制作日<a href="<?php echo $this->baseUrl('/admin/page/index/page/1/sort/create_date/order/desc') ?>">
                        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" />
                    </a>
                    <a href="<?php echo $this->baseUrl('/admin/page/index/page/1/sort/create_date/order/asc') ?>">
                        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" />
                    </a>
                </th>
                <th scope="col">制作者</th>
                <th scope="col">カテゴリー</th>
                <th scope="col">状態</th>
                <th scope="col">削除</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->pages as $page): ?>
            <tr<?php echo $this->cycle(array('', ' class="checkG"'))->next() ?>>
                <?php echo $this->partial('page-row.phtml', array('page' => $page, 'categoryForm' => $this->categoryForm, 'statusForm' => $this->statusForm)) ?>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    <?php echo $this->paginator //ページャーの表示 ?>
</div>
<!-- section END -->
