<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>ページの新規作成（プレビュー）</p>
</div>
<!-- topicpath END -->

<!-- section START --> 
<div class="section"> 

    <div class="hArea"> 

        <h3 id="textType">プレビュー</h3> 

    </div> 

    
    <form action="contribution_check.php" method="post" ENCTYPE="MULTIPART/FORM-DATA"> 

        <input type="hidden" id="user_id" name="user_id" value="0" /> 

        <ul> 
            <li class="inputAreaL"><a href="index.php">編集画面に戻る</a></li> 
            <li class="inputAreaL"><input type="submit" id="sub" name="sub" value="公開して保存" /></li> 
        </ul> 
        
        <p style="text-align:center;"><img src="<?php echo $this->baseUrl('images/preview.jpg'); ?>" width="500" height="238" /></p> 

    </form> 

</div> 
<!-- section END --> 
