<?php
/**
 * エラーメッセージ用のパーシャルファイル
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Install
 * @subpackage  View_Partials
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 1.2.0
 * @author      Takayuki Otake
 */
?>
<?php if ($this->errorForm->isErrors()): ?>
<div class="errorMessageArea">
<?php foreach ($this->errorForm->getMessages() as $messages): ?>
    <?php if (!is_array($messages)):?>
    <p class="clear"><?php echo $this->escape($messages) ?></p>
    <?php else: ?>
        <?php foreach ($messages as $message):?>
    <p class="clear"><?php echo $this->escape($message) ?></p>
        <?php endforeach ?>
    <?php endif ?>
<?php endforeach ?>
    <p>
        <a href="javascript:void(0)" onclick="hideErrorMessageArea()">OK</a>
    </p>
</div>
<?php endif ?>
