<?php
/**
 * ページャー用のパーシャルファイル
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Default
 * @package    View_Partial
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @author     suzuki-mar
 */
?>
<?php if ($this->pageCount): ?>

<div id="pageNav">
    <ul>
        <?php if (isset($this->previous)): ?>
        <!-- 前のページへのリンク -->
        <li>
            <a href="<?php echo $this->url(array('page' => $this->previous)) ?>">前へ</a>
        </li>
        <?php endif ?>
        <!-- ページ番号へのリンク -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
        <li class="navNumber">
            <a href="<?php echo $this->url(array('page' => $page)) ?>"><?php echo $page ?></a>
        </li>
        <?php else: ?>
        <li class="navNumber current">
            <span><?php echo $page ?></span>
        </li>
        <?php endif ?>
    <?php endforeach ?>
        <?php if (isset($this->next)): ?>
        <!-- 次のページへのリンク -->
        <li>
            <a href="<?php echo $this->url(array('page' => $this->next)) ?>">次へ</a>
        </li>
        <?php endif ?>
    </ul>
</div>
<?php endif ?>
