<?php
/**
 * アップロード済みのファイルを編集する画面
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Media
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      array        $this->mediaDataData   編集対象のファイル情報を収めた配列
 * @param      Zend_Form    $updateForm  ファイル編集用のフォームオブジェクト
 * @param      string       $fileSizeMax アップロードできる最大ファイルサイズ（'*KB'などの形式）
 * @param      array        $flashMessage フラッシュメッセージが入った配列
 * @author     akitsukada
 */
?>
<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>
        <a href="<?php echo $this->baseUrl('/admin/media') ?>">ファイルの追加・編集・削除</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p><?php echo $this->escape("「{$this->mediaData['name']}」({$this->mediaData['id']}.{$this->mediaData['type']})") ?>の編集</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">
    <div class="hAreaText">
        <h3 id="textType"><?php echo $this->escape("「{$this->mediaData['name']}」({$this->mediaData['id']}.{$this->mediaData['type']})") ?>の編集</h3>
    </div>
    <?php echo $this->partial('action-message.phtml', array('flashMessages' => $this->flashMessages)) ?>
    <?php echo $this->partial('error-message.phtml', array('errorForm' => $this->updateForm)) ?>

    <form action="<?php echo $this->updateForm->getAction() ?>" method="post" enctype="MULTIPART/FORM-DATA">
        <dl id="inputArea">
            <dt>
                <?php echo $this->updateForm->getElement('preExtension') ?>
                <?php if (($this->mediaData['type'] === 'pdf' || $this->mediaData['type'] === 'txt')
                                            && !$this->mediaData['mediaExists']): #PDF/TXTでファイルなし ?>
                <span class="attentionMessage">※アップロードされたファイル[<?php echo $this->mediaData['uploadUrl'] ?>]が見つかりません。</span>
                <?php else: ?>
                    <?php if ($this->mediaData['mediaExists'] && $this->mediaData['thumbExists']): #ファイルあり・サムネイルあり ?>
                    <a href="<?php echo $this->baseUrl($this->mediaData['uploadUrl']) ?>">
                        <img src="<?php echo $this->baseUrl($this->mediaData['thumbUrl']) ?>" alt="「<?php echo $this->escape($this->mediaData['name']) ?>」を表示" />
                    </a>
                    <?php endif ?>
                    <?php if ($this->mediaData['mediaExists'] && !$this->mediaData['thumbExists']): #ファイルあり・サムネイルなし ?>
                    <a href="<?php echo $this->baseUrl($this->mediaData['uploadUrl']) ?>">
                        「<?php echo $this->escape($this->mediaData['name']) ?>」を表示
                    </a>
                    <br />
                    <span class="attentionMessage">※サムネイル画像[<?php echo $this->mediaData['uploadUrl'] ?>]が見つかりません。</span>
                    <?php endif ?>
                    <?php if (!$this->mediaData['mediaExists'] && $this->mediaData['thumbExists']): #ファイルなし・サムネイルあり ?>
                    <img src="<?php echo $this->baseUrl($this->mediaData['thumbUrl']) ?>" alt="「<?php echo $this->escape($this->mediaData['name']) ?>」を表示" />
                    <br />
                    <span class="attentionMessage">※アップロードされたファイル[<?php echo $this->mediaData['uploadUrl'] ?>]が見つかりません。</span>
                    <?php endif ?>
                    <?php if (!$this->mediaData['mediaExists'] && !$this->mediaData['thumbExists']): #ファイルなし・サムネイルなし(何も表示しない) ?>
                    <span class="attentionMessage">※アップロードされたファイル[<?php echo $this->mediaData['uploadUrl'] ?>]が見つかりません。</span>
                    <?php endif ?>
                <?php endif ?>
            </dt>
            <dt>ファイル名</dt>
            <dd><?php echo $this->updateForm->getElement('name') ?></dd>
            <dt>説明</dt>
            <dd><?php echo $this->updateForm->getElement('comment') ?></dd>
            <dt>ファイル<span class="attentionMessage">※アップロードできるのは、1ファイル <?php echo $this->fileSizeMax ?> までです。</span></dt>
            <dd class="default"><?php echo $this->updateForm->getElement('upload_img') ?></dd>
            <dd><?php echo $this->updateForm->getElement('up') ?></dd>
        </dl>
    </form>

</div>
<!-- section END -->

