<?php
/**
 * ファイルのアップロードや編集、一覧表示の画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Media
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @author     akitsukada
 */
?>

<!-- topicPath START -->
<div id="topicPath">
<p><a href="../index.php">トップ</a><img
	src="<?php echo $this->baseUrl('images/topicPath.gif') ?>" width="6"
	height="11" alt="の中の" /></p>
<p>ファイルの追加・編集・削除</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">

<div class="topichAreaL">
<div class="topichAreaR">
<div class="topichArea">

<h3><img src="<?php echo $this->baseUrl('images/h_file.jpg') ?>"
	width="193" height="18" alt="ファイルの追加・編集・削除" /></h3>
</div>
</div>
</div>

<?php if (count($this->flashMessage)) : ?>
    <div id='messageArea'>
        <p><?php echo $this->flashMessage ?></p>
        <p><a href="javascript:void(0)" onclick="hideFlashMessage()">OK</a></p>
    </div>
<?php endif; ?>


<form action="<?php echo $this->baseUrl('/admin/media/create'); ?>" method="post" ENCTYPE="MULTIPART/FORM-DATA">
<dl id="inputArea">
	<?php echo $this->uploadForm->getElement('upload_img'); ?>
</dl>
<dl style="clear: both;">
	<dd><a href="#" onclick="addElement()">ファイル選択欄を増やす</a></dd> <?php // @todo 未対応 ?>
	<dt><span class="attentionMessage">※アップロードできるファイルは、1ファイル <?php echo $this->maxFileSize; ?> KBまでです。</span></dt>	
	<?php echo $this->uploadForm->getElement('up'); ?>
</dl>
</form>
<form action="#" method="post" id="searchBox"
	style="clear: both; margin-bottom: 15px;">

<div id="toggleArea">
<div style="margin-top: 10px;">
<?php echo $this->searchForm->getElement('fileType'); ?>
</div>
<p style="margin-top: 15px;">
<?php echo $this->searchForm->getElement('search'); ?>
</p>
</div>
</form>
<table
	summary="ファイル一覧の表です。編集ボタンから、ファイルの編集ができます。削除ボタンから削除ができます。サムネイルを押すとファイルを表示します。"
	cellpadding="0" cellspacing="0">
	<thead>
		<tr>
			<th scope="col" width="20%" id="tableFirst">表示</th>
			<th scope="col" width="40%">ファイル
				<a href="<?php 
				    echo $this->baseUrl('/admin/media/index') . '/page/1/type/' . $this->condition['type'] . '/sort/name/order/desc'; 
				?>" title="降順に並び替え">▼</a>
				<a href="<?php 
				    echo $this->baseUrl('/admin/media/index') . '/page/1/type/' . $this->condition['type'] . '/sort/name/order/asc'; 
				?>" title="昇順に並び替え">▲</a>
			</th>
			<th scope="col" width="13%">更新日
				<a href="<?php 
				    echo $this->baseUrl('/admin/media/index') . '/page/1/type/' . $this->condition['type'] . '/sort/update_date/order/desc'; 
				?>" title="降順に並び替え">▼</a>
				<a href="<?php 
				    echo $this->baseUrl('/admin/media/index') . '/page/1/type/' . $this->condition['type'] . '/sort/update_date/order/asc'; 
				?>" title="昇順に並び替え">▲</a>
			</th>
			<th scope="col" width="13%">アップロード日
				<a href="<?php 
				    echo $this->baseUrl('/admin/media/index') . '/page/1/type/' . $this->condition['type'] . '/sort/create_date/order/desc'; 
				?>" title="降順に並び替え">▼</a>
				<a href="<?php 
				    echo $this->baseUrl('/admin/media/index') . '/page/1/type/' . $this->condition['type'] . '/sort/create_date/order/asc'; 
				?>" title="昇順に並び替え">▲</a>
			</th>
			<th scope="col" width="7%">編集</th>

			<th scope="col" width="7%">削除</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	foreach ($this->mediaData as $cnt => $fileinfo) {
    ?>
	    <tr <?php echo $cnt % 2 == 0 ? 'class="checkG"' : ''; ?>>
            <td class="thumb">
                <a href="#" onclick=""> <!-- そのファイルを開く？  -->
                <img src="<?php echo $this->baseUrl($fileinfo['thumbUrl']); ?>" width="48" height="auto" />
                </a>
            </td>
            <td>
                <?php echo $fileinfo['name']; ?>[<?php echo $fileinfo['type']; ?>]
            </td>
            <td>
                <?php echo $fileinfo['createDate']; ?>
            </td>
            <td>
                <?php echo $fileinfo['updateDate']; ?>
            </td>
            <td>
                <a href="<?php echo $this->baseUrl('/admin/media/form/id/' . $fileinfo['id']); ?>">
                <img src="<?php echo $this->baseUrl('/images/btn_edit.png') ?>" alt='編集' width='27' height='27' />
                </a>
            </td>
            <td>
                <a href="#" onclick="
                	if (confirm('ファイル <?php echo $fileinfo['name']; ?> を削除しますか？')) {
                		location.href = '<?php echo $this->baseUrl('/admin/media/delete/id/' . $fileinfo['id']); ?>';
                	} 
                "> <!-- ダイアログ表示=>OK押下でデリート --> 
                <img src="<?php echo $this->baseUrl('/images/btn_delete.png') ?>" alt='削除' width='27' height='27' />
                </a>
            </td>
        </tr>
	    
	<?php 
	}
	?>
	</tbody>
</table>

<div id="pageNav">
<?php echo $this->paginator; //ページャーの表示 ?>
</div>

</div>

<!-- section END -->

<script type="text/javascript">
	function addElement() {
	    var element = document.createElement('dd');
	    element.innerHTML = '<input type="file" name="upload_img" id="upload_img" size="55" />';

	    var objBody = document.getElementById("inputArea");
	    objBody.appendChild(element);
	    // body要素にdivエレメントを追加
	}
</script>