<?php
/**
 * 動作環境の確認をするページ
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Install
 * @subpackage  View_Script_Check
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 1.6.0
 * @author      Takayuki Otake
 */
?>

<h1>インストール環境のチェック</h1>

<?php if ($this->allOk) : ?>
<p>
動作に必要な環境が揃っています！
</p>
<a href="<?php echo $this->baseUrl('/install/install') ?>">インストールへ進む</a>

<?php elseif ($this->required_ok) : ?>

<p>
最低限の動作に必要な環境が揃っていません。設定の仕方がわからない場合はシステム管理者に問い合わせてください。
</p>
<a href="<?php echo $this->baseUrl('/install/install') ?>">インストールへ進む</a>

<?php else : ?>

<p>
動作に必要な環境が揃っていません。設定の仕方がわからない場合は
</p>
<?php endif ?>

<?php if (count($this->dirErrors) > 0) : ?>
<div class="notice">
    <ul>

        <?php if (isset($this->dirErrors['media_upload'])) : ?>
        <li><code>public/media/upload</code>ディレクトリに書き込み権限がありません。管理画面でファイルをアップロードができません</li>
        <?php endif ?>

        <?php if (isset($this->dirErrors['media_thumb'])) : ?>
        <li><code>public/media/thumbnail</code>ディレクトリに書き込み権限がありません。管理画面でファイルをアップロードができません</li>
        <?php endif ?>

        <?php if (isset($this->dirErrors['configs'])) : ?>
        <li><code>application/configs/</code>ディレクトリに書き込み権限がありません。インストーラで設定ファイルの生成ができません</li>
        <?php endif ?>

    </ul>
</div>
<?php endif ?>

<div id="env_required">
    <h2>最低限の動作に必要な環境</h2>
    <?php if ($this->requiredOk) : ?>
    <p></p>
    <?php else : ?>
    </p></p>
    <?php endif ?>

    <div class="envDescription">
        <h3>PHP</h3>
        インストールされているバージョン：<?php echo PHP_VERSION ?>
        <?php if ('5.2.6' <= PHP_VERSION) : ?>
        <p class="">動作に必要なバージョンを満たしています</p>
        <?php else : ?>
        <p class="">動作には5.2.6以上のバージョンが必要です</p>
        <?php endif ?>

        <h3>PHP拡張</h3>
        <dl>
            <dt>
            php-pdo,php-mysql : データベースの接続に利用します
            </dt>
                <dd>
                <?php if ($this->phpExtensions['pdo'] && $this->phpExtensions['mysql']) : ?>
                ○インストールされています
                <?php else : ?>
                ×インストールされていません
                <?php endif ?>
                </dd>

            <dt>
            php-mbstring : 日本語等のマルチバイト文字の処理に利用します
            </dt>
                <dd>
                <?php if ($this->phpExtensions['mbstring']) : ?>
                ○インストールされています
                <?php else : ?>
                ×インストールされていません
                <?php endif ?>
                </dd>
        </dl>


        <h2>Apacheモジュール</h2>
    
        <h3>mod_rewrite</h3>
        <?php if ($this->apacheModules['mod_rewrite']) : ?>
        ○ロードされています
        <?php else : ?>
        ×ロードされていません
        <?php endif ?>

    </div>
</div>

<div id="env_recommand">
    <h2>推奨される動作環境</h2>
    <p>最低限の動作には必要ありませんが、より便利な機能が使えるようになります</p>

    <a style="display:none;" for="envAllDescription">詳細を見る</a>
    <div class="envDescription" id="envAllDescription">

        <h3>PHP拡張</h3>
        <dl>
            <dt>php-gd : 管理画面で画像のアップロードをするのに必要です</dt>
                <dd>
                <?php if ($this->phpExtensions['gd']) : ?>
                ○インストールされています
                <?php else : ?>
                ×インストールされていません
                <?php endif ?>
                </dd>
        </dl>
    
    </div>
</div>

