<?php
/**
 * 新規作成などの実行結果を表示します。
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Partial
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      array flashMessages アクションの実行結果のメッセージ配列
 * @author     suzuki-mar
 */
?>

<?php if (count($this->flashMessages)): ?>
    <div class="messageArea">
    <?php foreach ($this->flashMessages as $flashMessage): ?>
        <p class="clear"><?php echo $this->escape($flashMessage) ?></p>
    <?php endforeach ?>
        <p>
            <a href="javascript:void(0)" onclick="hideMessageArea()">OK</a>
        </p>
    </div>
<?php endif ?>
