<?php
/**
 * タグの追加・編集・削除画面内のタグ表示部分
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Partial
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      int         $index       インデックス番号
 * @param      Setuco_Form $editTagForm タグ編集フォーム
 * @param      array       $tag         タグ情報の配列
 * @author     charlesvineyard
 */
?>
<?php
    $form = clone($this->editTagForm);
    $form->setAttrib('id', $form->getAttrib('id') . $this->index);
    $form->getElement('tag')
         ->setValue($this->tag['name'])
         ->setAttrib('id', $form->getElement('tag')->getAttrib('id') . $this->index);
    $form->getElement('id')
         ->setValue($this->tag['id'])
         ->setAttrib('id', $form->getElement('id')->getAttrib('id') . $this->index);
    $form->getElement('preTag')
         ->setValue($this->tag['name'])
         ->setAttrib('id', $form->getElement('preTag')->getAttrib('id') . $this->index);
    $form->getElement('sub')
         ->setAttrib('id', $form->getElement('sub')->getAttrib('id') . $this->index);
    $form->getElement('cancel')
         ->setAttrib('id', $form->getElement('cancel')->getAttrib('id') . $this->index);
?>
<td>
    <span class="tagView"><?php echo $this->escape($this->tag['name']) ?></span>
    <div class="tagEdit"><?php echo $form ?></div>
</td>
<td>
    <a href="javascript:void(0)" onclick="showTagEdit(this)">
        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_edit.png') ?>" alt="編集" width="27" height="27" />
    </a>
</td>
<td>
    <a href="javascript:void(0)" onclick="confirmDeleteRedirect('<?php echo $this->baseUrl("/admin/tag/delete/id/{$this->tag['id']}") ?>', '<?php echo $this->escape($this->tag['name']) ?>');">
        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_delete.png') ?>" alt="削除" width="27" height="27" />
    </a>
</td>