<?php
/**
 * 閲覧側のフッター
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $siteInfos  サイト情報       
 * @author      suzuki-mar
 */
?>

<p id='copyright'>Copyright&nbsp;&copy;&nbsp;<?php echo $this->siteInfos['start_year'] ?>&nbsp;
<?php echo $this->siteInfos['name'] ?>&nbsp;AllRight&nbsp;reserved.</p>
