<?php
/**
 * 閲覧側のヘッター
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $siteInfos  サイト情報       
 * @author      suzuki-mar
 */
?>

<div id="header_innerR"> 
    <div id="header_inner"> 

        <h1><a href="<?php echo $this->baseUrl('') ?>" tabindex="1"><?php echo $this->escape($this->siteInfos['name']) ?></a></h1>

        <form action="<?php echo $this->baseUrl('/page/search/') ?>" method="get">
            <dl>
                <dt><label for="keyword">フリーワード検索</label></dt>
                <dd><input type="text" name="query" id="keyword" value="<?php echo mb_strlen($this->keyword, 'UTF-8') > 0 ? $this->keyword : 'キーワードを入力して下さい' ?>" onfocus="if (this.value == 'キーワードを入力して下さい') { this.value=''; }" onblur="if(this.value == '') { this.value='キーワードを入力して下さい'; }" tabindex="2" /></dd>
            </dl>
            <p><input type="submit" value="検索" tabindex="3" /></p>
        </form>

        <p id="description"><?php echo $this->escape($this->siteInfos['comment']) ?></p>

    </div> 
 </div> 
