<?php
/**
 * 閲覧側のヘッター
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category    Setuco
 * @package     Default
 * @subpackage  View_Layout
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 0.1.0
 * @param       array   $siteInfos  サイト情報       
 * @author      suzuki-mar
 */
?>

<div id="header_innerR"> 
    <div id="header_inner"> 

        <h1><a href="<?php echo $this->baseUrl('') ?>" tabindex="1"><?php echo $this->escape($this->siteInfos['name']) ?></a></h1>

        <form action="<?php echo $this->baseUrl('/page/search/') ?>" method="get">
            <dl>
                <dt><label for="keyword">フリーワード検索</label></dt>
                <dd><input type="text" name="query" id="keyword" value="<?php echo mb_strlen($this->keyword, 'UTF-8') > 0 ? $this->keyword : 'キーワードを入力して下さい' ?>" onfocus="if (this.value == 'キーワードを入力して下さい') { this.value=''; }" onblur="if(this.value == '') { this.value='キーワードを入力して下さい'; }" tabindex="2" /></dd>
            </dl>
            <p><input type="submit" value="検索" tabindex="3" /></p>
        </form>

        <p id="description"><?php echo $this->escape($this->siteInfos['comment']) ?></p>

    </div> 
 </div> 
