<?php
$this->headTitle('日本電子専門学校電設部')->setSeparator(' / ');;     // TODO DBからサイトタイトルを取得する
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ja" xml:lang="ja">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="content-style-type" content="text/css" />
        <meta http-equiv="content-script-type" content="text/javascript" />

        <meta name="author" content="" />        <?php // TODO DBから取得する? ?>        
        <meta name="copyright" content="日本電子専門学校 電設部?" />   <?php // TODO DBから取得する ?>   
        <meta name="generator" content="SetucoCMS" />
        <meta http-equiv="imagetoolbar" content="no" />

        <meta name="description" content="日本電子専門学校電設部SetucoCMSプロジェクトです。" />
        <meta name="keywords" content="せつこ,俺だ,結婚,してくれ" />

        <link rel="start" href="<?php echo $this->baseUrl('') ?>" title="このブログのトップページ" />

        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('/css/style.css') ?>" media="screen" />


        <?php echo $this->headTitle();  ?>
    </head>
    <body>
    
        <!-- wrapper START -->
        <div id="wrapper">
        
            <!-- header START -->
            <div id="header_innerL">
                <?php echo $this->render('header.phtml'); ?>
            </div>
            <!-- header END -->

            <!-- content START -->
            <div id="content">

                <!-- mainContent START -->
                <div id="mainContent">
                    <?php echo $this->layout()->content ?>
                </div>
                <!-- mainContent END -->
        
                <!-- subContent START -->
                <div id="subContent">
                        <?php echo $this->render('navi.phtml') ?>
                </div>
                <!-- subContent END -->

            </div>
            <!-- content END -->

            <?php echo $this->render('footer.phtml') ?>

        </div>
        <!-- container END -->
        
    </body>
</html>
