<!-- navArea START --> 
<div id="navArea">

    <!-- navList START -->
    <div class="navList">

        <h3>カテゴリー</h3>

        <ul>
            <li><a href='<?php echo "{$this->baseUrl('')}index/category"?>'>about</a></li>
            <li><a href='<?php echo "{$this->baseUrl('')}index/category"?>'>contents</a></li>
            <li><a href='<?php echo "{$this->baseUrl('')}index/category"?>'>link</a></li>
            <li><a href='<?php echo "{$this->baseUrl('')}index/category"?>'>report</a></li>
            <li><a href='<?php echo "{$this->baseUrl('')}index/category"?>'>test</a></li>
            <li><a href='<?php echo "{$this->baseUrl('')}index/category"?>'>新規カテゴリー</a></li>
            <li><a href='<?php echo "{$this->baseUrl('')}index/category"?>'>未分類</a></li>
        </ul>

    </div>
    <!-- navList END -->

    <!-- navList START -->
    <div class="navList">
        <h3>タグクラウド</h3> 
                    
            <ul id="tagCloud"> 
                    
                <li class="level10"><a href="#">タグ10</a><li> 
                <li class="level1"><a href="#">タグ1</a><li> 
                <li class="level5"><a href="#">タグ5</a><li> 
                <li class="level2"><a href="#">タグ2</a><li> 
                <li class="level7"><a href="#">タグ7</a><li> 
                <li class="level6"><a href="#">タグ6</a><li> 
                <li class="level3"><a href="#">タグ3</a><li> 
                <li class="level8"><a href="#">タグ8</a><li> 
                <li class="level9"><a href="#">タグ9</a><li> 
                <li class="level4"><a href="#">タグ4</a><li> 
                        
           </ul> 
                    
    </div>
     <!-- navList END -->    
     
 </div>
<!-- navArea END --> 
