<?php
/**
 * タグの追加・編集・削除画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Tag
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version    
 * @since      File available since Release 0.1.0
 * @param      
 * @author     charlesvineyard
 */
?>
<!-- topicPath START --> 
<div id="topicPath"> 
    <p><a href="/admin/index">トップ</a><img src="/images/topicPath.gif" width="6" height="11" alt="の中の" /></p> 
    <p>タグの追加・編集・削除</p> 
</div> 
<!-- topicpath END --> 

<!-- section START --> 
<div class="section"> 

    <div class="topichAreaL"> 

        <div class="topichAreaR"> 

            <div class="topichArea"> 

            <h3><img src="/images/h_tagAll.jpg" width="168" height="18" alt="タグの追加・編集・削除" /></h3> 

       </div> 

    </div> 

    </div> 

    <form action="tag_edit.php" method="post"> 

        <p class="default"><input type="text" id="tag_name" name="tag_name" class="defaultInput" value="新規タグ" /><input type="submit" id="sub" name="sub" value="追加" /></p> 

        <table summary="タグ一覧の表です。タグの追加・編集・削除ができます。" cellpadding="0" cellspacing="0"> 
            <colrougp> 
                <col width="80%" /> 
                <col width="10%" /> 
                <col width="10%" /> 
            </colgroup> 
           <thead> 
               <tr> 
                   <th scope="col" id="tableFirst">タグ名<a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" /></a><a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" /></a></th> 
                   <th scope="col">編集</th> 
                   <th scope="col">削除</th> 
               </tr> 
           </thead> 

           <tbody> 
			   <?php foreach($this->tags as $value): ?>
               <tr> 
                   <td><?php echo $value["name"] ?></td>
                   <td><a href='/admin/tag/update/id/<?php echo $value['id'] ?>'><img src='/images/btn_edit.png' alt='編集' width='27' height='27' /></a></td>
                   <input type='hidden' id='tag_id' name='tag_id' value='<?php echo $value["id"] ?>' />
                   <input type='hidden' id='tag_no' name='tag_no' value='' />
                   <td><a href='/admin/tag/delete/id/<?php echo $value['id'] ?>' onclick='flg(1);'><img src='/images/btn_delete.png' alt='削除' width='27' height='27' /></a></td>
               </tr> 
			   <?php endforeach; ?>
           </tbody> 
        </table> 

    </form> 

    <?php echo $this->paginator; //ページャーの表示 ?>

</div> 
<!-- section END --> 
