<!-- topicPath START --> 
<div id="topicPath"> 
    <p><a href="/admin/index">トップ</a><img src="/images/topicPath.gif" width="6" height="11" alt="の中の" /></p> 
    <p>タグの追加・編集・削除</p> 
</div> 
<!-- topicpath END --> 

<!-- section START --> 
<div class="section"> 

    <div id="topichAreaL"> 

        <div id="topichAreaR"> 

            <div id="topichArea"> 

            <h3><img src="/images/h_tagAll.jpg" width="168" height="18" alt="タグの追加・編集・削除" /></h3> 

       </div> 

    </div> 

    </div> 

    <form action="tag_edit.php" method="post"> 

        <p style="margin-bottom:10px;"><input type="text" id="tag_name" name="tag_name" value="新規タグ" /><input type="submit" id="sub" name="sub" value="追加" /></p> 

        <table summary="タグ一覧の表です。タグの追加・編集・削除ができます。" cellpadding="0" cellspacing="0"> 

           <thead> 
               <tr> 
                   <th scope="col" width="80%" id="tableFirst">タグ名<a href="#">▼</a><a href="#">▲</a></th> 
                   <th scope="col" width="10%">編集</th> 
                   <th scope="col" width="10%">削除</th> 
               </tr> 
           </thead> 

           <tbody> 
			   <?php foreach($this->tags as $value): ?>
               <tr> 
                   <td><?php echo $value["name"] ?></td>
                   <td><a href='/admin/tag/update/id/<?php echo $value['id'] ?>'><img src='/images/btn_edit.png' alt='編集' widrh='27' height='27' /></a></td>
                   <input type='hidden' id='tag_id' name='tag_id' value='<?php echo $value["id"] ?>' />
                   <input type='hidden' id='tag_no' name='tag_no' value='' />
                   <td><a href='/admin/tag/delete/id/<?php echo $value['id'] ?>' onclick='flg(1);'><img src='/images/btn_delete.png' alt='削除' widrh='27' height='27' /></a></td>
               </tr> 
			   <?php endforeach; ?>
           </tbody> 
        </table> 

    </form> 

    <?php echo $this->paginator; //ページャーの表示 ?>

</div> 
<!-- section END --> 
