<?php
/**
 * タグの追加・編集・削除画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Tag
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      string         flashMessage フラッシュメッセージ
 * @param      array          tags         タグの一覧情報
 * @param      Setuco_Form    editTagForm  タグ編集フォーム
 * @param      Zend_Paginator paginator    ページネーター
 * @author     charlesvineyard
 */
?>

<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>タグの追加・編集・削除</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">
    <div class="hAreaL">
        <div class="hAreaR">
            <div class="hArea">
                <h3>
                    <img src="<?php echo $this->baseUrl('/images/admin/tag/h_tagAll.jpg') ?>" width="168" height="18" alt="タグの追加・編集・削除" />
                </h3>
            </div>
        </div>
    </div>
    <?php if (count($this->flashMessages)): ?>
        <div id="messageArea">
        <?php foreach ($this->flashMessages as $flashMessage): ?>
            <p><?php echo $flashMessage ?></p>
        <?php endforeach ?>
            <p>
                <a href="javascript:void(0)" onclick="hideFlashMessage()">OK</a>
            </p>
        </div>
    <?php endif ?>

    <?php echo $this->newTagForm ?>

    <table summary="タグ一覧の表です。タグの追加・編集・削除ができます。" cellpadding="0" cellspacing="0">
        <colgroup>
            <col width="80%" />
            <col width="10%" />
            <col width="10%" />
        </colgroup>
        <thead>
            <tr>
                <th scope="col" id="tableFirst">タグ名<a href="<?php echo $this->baseUrl('/admin/tag/index/page/1/order/desc') ?>">
                        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" />
                    </a>
                    <a href="<?php echo $this->baseUrl('/admin/tag/index/page/1/order/asc') ?>">
                        <img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" />
                    </a>
                </th>
                <th scope="col">編集</th>
                <th scope="col">削除</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->tags as $tag): ?>
            <tr<?php echo $this->cycle(array('', ' class="check"'))->next() ?>>
                <?php echo $this->partial('tag-row.phtml', array('tag' => $tag, 'editTagForm' => $this->editTagForm)) ?>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php echo $this->paginator //ページャーの表示 ?>
</div>
<!-- section END -->