<?php
/**
 * フォームのエラーメッセージを表示します。
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Install
 * @subpackage View_Partial
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      array flashMessages アクションの実行結果のメッセージ配列
 * @author     suzuki-mar
 */
?>
<?php if ($this->errorForm->isErrors()): ?>
<div class="errorMessageArea">
<?php foreach ($this->errorForm->getMessages() as $messages): ?>
    <?php if (!is_array($messages)):?>
    <p class="clear"><?php echo $this->escape($messages) ?></p>
    <?php else: ?>
        <?php foreach ($messages as $message):?>
    <p class="clear"><?php echo $this->escape($message) ?></p>
        <?php endforeach ?>
    <?php endif ?>
<?php endforeach ?>
    <p>
        <a href="javascript:void(0)" onclick="hideErrorMessageArea()">OK</a>
    </p>
</div>
<?php endif ?>
