<?php
/**
 * ログイン画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Login
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      string      $errors エラー情報
 * @param      Setuco_Form $form   ログインフォーム
 * @author     Yuu Yamanaka
 */
?>

<h1>
    <img src="<?php echo $this->baseUrl('/images/admin/login/loginLogo.gif') ?>" width="245" height="69" alt="せつこCMS  サイト制作に自由さと楽しさを" />
</h1>

<?php echo $this->partial('error-message.phtml', array('errorForm' => $this->form)) ?>
<?php echo $this->partial('action-message.phtml', array('flashMessages' => $this->flashMessages)) ?>

<form enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->form->getAction() ?>">
    <dl class="straight">
        <?php echo $this->form->getElement('login_id') . "\n" ?>
        <?php echo $this->form->getElement('password') . "\n" ?>
    </dl>
    <?php echo $this->form->getElement('sub') . "\n" ?>
</form>

