<?php
/**
 * ログイン画面
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Login
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      string      $errors エラー情報
 * @param      Setuco_Form $form   ログインフォーム
 * @author     Yuu Yamanaka
 */
?>

<h1>
    <img src="<?php echo $this->baseUrl('/images/admin/login/loginLogo.gif') ?>" width="245" height="69" alt="せつこCMS  サイト制作に自由さと楽しさを" />
</h1>

<?php echo $this->partial('error-message.phtml', array('errorForm' => $this->form)) ?>
<?php echo $this->partial('action-message.phtml', array('flashMessages' => $this->flashMessages)) ?>

<form enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->form->getAction() ?>">
    <dl class="straight">
        <?php echo $this->form->getElement('login_id') . "\n" ?>
        <?php echo $this->form->getElement('password') . "\n" ?>
    </dl>
    <?php echo $this->form->getElement('sub') . "\n" ?>
</form>

