<?php
/**
 * インストーラのフォーム入力の確認ページ
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Install
 * @subpackage  View_Script_Install
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 1.2.0
 * @author      ErinaMikami, suzuki-mar, Takayuki Otake
 */
?>
<h2>入力情報確認</h2>
<p>以下の情報で登録して、よろしいでしょうか？</p>
<dl>
  <dt>管理者アカウントID</dt>
    <dd><?php echo $this->inputValues['account_id'] ?></dd>
  <dt>管理者パスワード</dt>
    <dd>****(入力OK)</dd>
  <dt>サイト名</dt>
    <dd><?php echo $this->inputValues['site_name'] ?></dd>
  <dt>サイトURL</dt>
    <dd><?php echo $this->inputValues['site_url'] ?></dd>
  <dt>サイトの説明</dt>
    <dd><?php echo $this->inputValues['site_comment'] ?></dd>
  <dt>データベース名</dt>
    <dd><?php echo $this->inputValues['db_host'] ?></dd>
  <dt>データベース名</dt>
    <dd><?php echo $this->inputValues['db_name'] ?></dd>
  <dt>接続ユーザー名</dt>
    <dd><?php echo $this->inputValues['db_user'] ?></dd>
  <dt>パスワード</dt>
    <dd>****(入力OK)</dd>
</dl>

<div class="form-actions">
  <form method="post" action="<?php echo $this->baseUrl('/install/install/action') ?>">
    <input type="hidden" name="account_id" value="<?php echo $this->inputValues['account_id'] ?>">
    <input type="hidden" name="account_pass" value="<?php echo $this->inputValues['account_pass'] ?>">
    <input type="hidden" name="account_pass_check" value="<?php echo $this->inputValues['account_pass_check'] ?>">
    <input type="hidden" name="site_name" value="<?php echo $this->inputValues['site_name'] ?>">
    <input type="hidden" name="site_comment" value="<?php echo $this->inputValues['site_comment'] ?>">
    <input type="hidden" name="site_url" value="<?php echo $this->inputValues['site_url'] ?>">
    <input type="hidden" name="db_host" value="<?php echo $this->inputValues['db_host'] ?>">
    <input type="hidden" name="db_name" value="<?php echo $this->inputValues['db_name'] ?>">
    <input type="hidden" name="db_user" value="<?php echo $this->inputValues['db_user'] ?>">
    <input type="hidden" name="db_pass" value="<?php echo $this->inputValues['db_pass'] ?>">

    <input type="submit" name="commit" value="送信">
  </form>

  <form method="post" action="<?php echo $this->baseUrl('/install/install/') ?>">
    <input type="hidden" name="account_id" value="<?php echo $this->inputValues['account_id'] ?>">
    <input type="hidden" name="account_pass" value="<?php echo $this->inputValues['account_pass'] ?>">
    <input type="hidden" name="account_pass_check" value="<?php echo $this->inputValues['account_pass_check'] ?>">
    <input type="hidden" name="site_name" value="<?php echo $this->inputValues['site_name'] ?>">
    <input type="hidden" name="site_comment" value="<?php echo $this->inputValues['site_comment'] ?>">
    <input type="hidden" name="site_url" value="<?php echo $this->inputValues['site_url'] ?>">
    <input type="hidden" name="db_host" value="<?php echo $this->inputValues['db_host'] ?>">
    <input type="hidden" name="db_name" value="<?php echo $this->inputValues['db_name'] ?>">
    <input type="hidden" name="db_user" value="<?php echo $this->inputValues['db_user'] ?>">
    <input type="hidden" name="db_pass" value="<?php echo $this->inputValues['db_pass'] ?>">

    <input type="submit" value="戻る">
  </form>
</div>
