<?php
/**
 * カテゴリーの新規作成、編集 一覧表示の画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Category
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @author     suzuki-mar
 */
?>

<?php
?>

<!-- topicPath START -->
<div id="topicPath">
    <p><a href="<?php echo $this->baseUrl('/'); ?>">トップ</a><img src="<?php echo $this->baseUrl('/images/topicPath.gif')?>" width="6" height="11" alt="の中の" /></p>
    <p>カテゴリーの追加・編集・削除</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">

    <div class="topichAreaL">

        <div class="topichAreaR">

            <div class="topichArea">

                <h3><img src="<?php echo $this->baseUrl('/images/h_catAll.jpg')?>" width="208" height="18" alt="カテゴリーの追加・編集・削除" /></h3>

            </div>

        </div>

    </div>

    

        <form action="<?php echo $this->baseUrl('/admin/category/create');?>" method="post">
        <p class="default">
        <?php echo $this->createForm->getElement('cat_name'); ?>
        <?php echo $this->createForm->getElement('sub'); ?>
        </p>
        </form>

        <table summary="カテゴリー一覧の表です。カテゴリーの追加・編集・削除ができます。" cellpadding="0" cellspacing="0">
            <colrougp> 
                <col width="80%" /> 
                <col width="10%" /> 
                <col width="10%" /> 
            </colgroup>
            <thead>
                <tr>
                    <th scope="col" id="tableFirst">カテゴリー名<a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" /></a><a href="#"><img src="<?php echo $this->baseUrl('images/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" /></a></th>
                    <th scope="col">編集</th>
                    <th scope="col">削除</th>
                </tr>

            </thead>

            <tbody>

<?php foreach($this->categories as $value): ?>

<?php if($value['is_check']): //checkしているか? ?>
<tr class='checkG'>
<?php else: ?>
<tr>
<?php endif; ?>

<?php if ($value['id'] !== false): //登録したカテゴリーか　編集削除できるか ?> 

<?php //タグを編集するか ?>
<?php if ($value['id'] == $this->editId): ?>
<td> 
<form action="<?php echo $this->baseUrl('/admin/category/update')?>" method="post">

<?php
echo $this->addForm->getElement('name')->setValue($value['name']);
echo $this->addForm->getElement('id')->setValue($value['id']);
echo $this->addForm->getElement('sub');
?>

</form>
</td>

<?php else: ?>
<td><?php echo $value['name'] ?></td>

<?php endif; ?>

<td><a href='<?php echo $this->baseUrl("/admin/category/index/page/{$this->page}/id/{$value['id']}")?>'><img src='<?php echo $this->baseUrl('/images/btn_edit.png')?>' alt='編集' width='27' height='27' /></a></td>
<input type='hidden' id='cat_id' name='cat_id' value='<?php echo $value['id'] ?>' />
<input type='hidden' id='cat_no' name='cat_no' value='' />
<td><a href='#' onclick='flg(<?php echo $value['id']?>);'><img src='<?php echo $this->baseUrl('/images/btn_delete.png')?>' alt='削除' width='27' height='27' /></a></td>

<?php else: //デフォルトのカテゴリー 編集削除できない ?>
<td>未分類<span id='autoCatMessage'>（※カテゴリー未選択時に自動選択されるカテゴリーです）</span></td><td>&nbsp;</td><td>&nbsp;</td>

<?php endif; ?>


</tr>
<?php endforeach; ?>

           </tbody>

        </table>

    </form>

    <?php echo $this->paginator; ?>
    
</div>
<!-- section END -->

<?php //htmlのheadタグで出力するためにキャプチャーする
$this->headScript()->captureStart() ?>
<!--
function flg(id){
    var flg;　//真偽を入れる変数の宣言

        flg=confirm("本当に削除してよろしいですか？"); //真偽の代入

    if (flg==true){
        location.href='index.php?delete='+id;
    }
}
// -->
<?php $this->headScript()->captureEnd() ?>


