<?php
/**
 * カテゴリーの新規作成、編集 一覧表示の画面
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Category
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      Zend_Paginator   $paginator    ページャークラス 
 * @param      Setuco_Form      $createForm   カテゴリーを新規作成するフォームクラス
 * @param      Setuco_Form      $updateForm   カテゴリーを編集するフォームクラス
 * @param      array            $categories   一覧ページで表示するカテゴリーデータ
 * @param      array[option]   $flashMessage 新規作成、編集、削除の実行結果のメッセージ
 * @author     suzuki-mar
 */
?>

<!-- topicPath START -->
<div id="topicPath">
    <p>
        <a href="<?php echo $this->baseUrl('/admin') ?>">トップ</a>
        <img src="<?php echo $this->baseUrl('/images/admin/share/topicPath.gif') ?>" width="6" height="11" alt="の中の" />
    </p>
    <p>カテゴリーの追加・編集・削除</p>
</div>
<!-- topicpath END -->

<!-- section START -->
<div class="section">
    <div class="topichAreaL">
        <div class="topichAreaR">
            <div class="topichArea">
                <h3><img src="<?php echo $this->baseUrl('/images/admin/category/h_catAll.jpg')?>" width="208" height="18" alt="カテゴリーの追加・編集・削除" /></h3>
            </div>
        </div>
    </div>

    <?php echo $this->partial('action-message.phtml', array('flashMessages' => $this->flashMessages)); ?>

    
        <form action="<?php echo $this->baseUrl('/admin/category/create');?>" method="post">
            <p class="default">
                <input type="text" name="cat_name" id="cat_name" class="defaultInput" value="新規カテゴリー" />
                <input type="submit" class="sub" value="追加" />
            </p> 
        </form>

        <table summary="カテゴリー一覧の表です。カテゴリーの追加・編集・削除ができます。" cellpadding="0" cellspacing="0">
            <colgroup> 
                <col width="80%" /> 
                <col width="10%" /> 
                <col width="10%" /> 
            </colgroup>
            <thead>
                <tr>
                    <th scope="col" id="tableFirst">
                        カテゴリー名
                        <a href="<?php echo $this->baseUrl('/admin/category/index/sort/desc')?>"><img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_descending.gif') ?>" width="15" height="15" alt="降順に並び替え" /></a>
                        <a href="<?php echo $this->baseUrl('/admin/category/index/sort/asc')?>"><img src="<?php echo $this->baseUrl('/images/admin/share/btn_sort_ascending.gif') ?>" width="15" height="15" alt="昇順に並び替え" /></a>
                    </th>
                    <th scope="col">編集</th>
                    <th scope="col">削除</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->categories as $key => $value): ?>

                <?php if ($key % 2 === 0): //配列のループが偶数か ?>
                <tr>
                <?php else: ?>
                <tr class='check'>
                <?php endif; ?>

                <?php if ($value['id'] !== false): //登録したカテゴリーか　編集削除できるか ?> 
                <?php //タグを編集するか ?>
                <?php if ($value['id'] == $this->editId): ?>

                <td> 
                    <form action="<?php echo $this->baseUrl('/admin/category/update')?>" method="post">
                        <p>
                            <input type="text" name="name" id="name<?php echo $value['id']?>" value="<?php echo $value['name']?>"　/>
                            <input type="hidden" name="id" id="id<?php echo $value['id']?>" value="<?php echo $value['id']?>" />
                            <input type="hidden" name="parent_id" id="parent_id<?php echo $value['id']?>" value="<?php echo $value['parent_id']?>" />
                            <input type="submit" class="sub" value="保存" />
                        </p>
                    </form> 
                </td> 

                <?php else: ?>
                <td><?php echo $value['name'] ?></td>

                <?php endif; ?>

                <td>
                    <a href='<?php echo $this->baseUrl("/admin/category/index/page/{$this->page}/id/{$value['id']}")?>'><img src='<?php echo $this->baseUrl('/images/admin/share/btn_edit.png')?>' alt='編集' width='27' height='27' /></a>
                    <form action="<?php echo $this->baseUrl('/admin/category/update')?>" method="get">
                        <p>
                            <input type='hidden' id='cat_id<?php echo $value['id']?>' name='cat_id' value='<?php echo $value['id'] ?>' />
                            <input type='hidden' id='cat_no<?php echo $value['id']?>' name='cat_no' value='' />
                            <input type='hidden' name='sort' value='<?php echo $this->sort?>' />
                        </p>
                    </form>
                </td>
                <td>
                    <?php
                    $redirectUrl = $this->baseUrl("/admin/category/delete/id/{$value['id']}");
                    $deleteItem  = "{$value['name']}のカテゴリー";
                    ?>
                    <a href='javascript:void(0)' onclick='confirmDeleteRedirect("<?php echo $redirectUrl ?>", "<?php echo $deleteItem ?>");'><img src='<?php echo $this->baseUrl('/images/admin/share/btn_delete.png')?>' alt='削除' width='27' height='27' /></a>
                </td>

                <?php endif; ?>


            </tr>
            <?php endforeach; ?>

           </tbody>
        </table>

    <?php echo $this->paginator; ?>
    
</div>
<!-- section END -->

<?php //htmlのheadタグで出力するためにキャプチャーする
$this->headScript()->captureStart() ?>
<!--
function confirmDeleteRedirect(url, item){

    if (confirm(item + "を本当に削除してよろしいですか？")) {
        location.href = url;
    }
}
// -->
<?php $this->headScript()->captureEnd() ?>
