<?php
/**
 * インストーラのTOPページ
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category    Setuco
 * @package     Install
 * @subpackage  View_Script_Index
 * @license     http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright   Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since       File available since Release 1.2.0
 * @author      Takayuki Otake
 */
?>
<h2>SetucoCMSへようこそ。</h2>
<p>簡単にサイトを制作できるだけでなく、<br />あなたのモチベーションがアップする楽しい機能を用意してます。<br />
今すぐ楽しいサイト制作を始めましょう！</p>
<p><a href="<?php echo $this->baseUrl('/install/install') ?>">セットアップに進む =&gt;</a></p>
