<?php
/**
 * ナビゲーション画面
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category   Setuco
 * @package    Admin
 * @subpackage View_Script_Navigation
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      array $navInfos ナビゲーション情報の配列
 * @author     charlesvineyard
 */
?>
<!-- gNav START -->
<ul id="gNav">
<?php foreach ($this->navInfos as $navigation): ?>
    <li>
    <?php if ($navigation['id'] == 'index'): ?>
        <a href="<?php echo $navigation['href'] ?>">
            <img src="<?php echo $navigation['src'] ?>" alt="<?php echo $navigation['label'] ?>" width="150" height="30" />
        </a>
    <?php else: ?>
        <dl>
            <dt>
                <a href="<?php echo $navigation['href'] ?>">
                    <img src="<?php echo $navigation['src'] ?>" alt="<?php echo $navigation['label'] ?>" width="150" height="30" />
                </a>
            </dt>
        <?php if (count($navigation['childrenArr'])): ?>
            <?php foreach ($navigation['childrenArr'] as $child): ?>
            <dd<?php echo ($child['isActive']) ? ' id="active"' : '' ?>>
                <a href="<?php echo $child['href'] ?>"><?php echo $child['label'] ?></a>
            </dd>
            <?php endforeach ?>
        <?php endif ?>
        </dl>
    <?php endif ?>
    </li>
<?php endforeach ?>
</ul>
<!-- gNav END -->
