<?php
/**
 * あるカテゴリに属するページ一覧を表示するページ
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Default
 * @subpackage View_Script_Page
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      entries カテゴリに属するページのデータを収めた配列
 * @param      category カテゴリのデータ
 * @author     akitsukada
 */
?>
<?php if (count($this->entries) > 0): ?>
    <p><?php echo "カテゴリー「{$this->escape($this->category['name'])}」" ?>のページ一覧</p>
    <?php foreach($this->entries as $id => $entry): ?>
    <!-- entry START -->
    <div class="entry">
        <div class="entryHead">
            <h2><a href="<?php echo $this->baseUrl('page/show/id/' . $entry['id']) ?>"><?php echo $this->escape($entry['title']) ?></a></h2>
            <p><?php echo date('Y年m月d日', strtotime($entry['update_date'])) ?></p>
        </div>
        <dl class="category">
            <dt>カテゴリー：</dt>
                <dd><a href="<?php echo $this->baseUrl('page/category/id/' . $this->category['id']) ?>" ><?php echo $this->escape($this->category['name']) ?></a></dd>
        </dl>
        <div class="entryBody">
            <?php echo mb_substr($entry['contents'], 0, 50, 'UTF-8') . "\n" //todo コンテンツを5行のみ表示する（今は適当に50を指定） ?>
            <p><a href="<?php  echo $this->baseUrl('page/show/id/' . $entry['id']) ?>">続きを読む</a></p>
        </div>
        <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>
    </div>
    <!-- entry END -->
    <?php endforeach ?>
    <?php echo $this->paginator //ページャーの表示 ?>
<?php else: ?>
    <p>カテゴリー「<?php echo $this->escape($this->category['name']) ?>」にはページがありません。</p>
<?php endif ?>