<?php if (count($this->entries) > 0): ?>

    <p>「<?php echo $this->category['name'] ?>」の一覧</p>
    <?php foreach($this->entries as $id => $entry): ?>
    <?php $accountName = is_null($entry['account_name']) ? '誰？' : $entry['account_name'] ?>
    <!-- entry START -->
    <div class="entry">
        <div class="entryHead">
            <h2><a href="<?php echo $this->baseUrl('page/show/id/' . $entry['id']) ?>"><?php echo $entry['title'] ?></a></h2>
            <p><?php echo $entry['update_date'] ?></p>
        </div>

        <dl class="category">
            <dt>カテゴリー：</dt>
                <dd><?php echo $this->category['name'] ?></dd>
            <dt>投稿者：</dt>
                <dd><?php echo $accountName ?></dd>
        </dl>

        <div class="entryBody">
            <?php echo $entry['contents'] ?>   
        </div>

        <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>

    </div>
    <!-- entry END -->
    <?php endforeach ?>

    <?php echo $this->paginator //ページャーの表示 ?>

<?php else: ?>

    <p>カテゴリー「<?php echo $this->category['name'] ?>」には記事がありません。</p>

<?php endif ?>