<?php
/**
 * キーワード検索の結果、該当するページが１個もなかったときに表示されるページ
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category   Setuco
 * @package    Default
 * @subpackage View_Script_Page
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      keyword 検索に使われた文字列
 * @param      resultCount 検索結果の件数
 * @author     akitsukada
 */
?>
<!-- entry START -->
<div class="entry">
    <div class="entryHead">
        <h2><span>「<?php echo $this->escape($this->keyword) ?>」の検索結果（<?php echo $this->resultCount ?>件）</span></h2>
    </div>
    <div class="entryBody">
        <p>「<?php echo $this->escape($this->keyword) ?>」に一致するページはありませんでした。<br />以下のことを確認して再度検索してみてください。</p>
        <ul class="list">
            <li>キーワードに誤字・脱字はありませんか？</li>
            <li>キーワードは長すぎませんか？</li>
            <li>一般的なキーワードに変えてみてください。</li>
        </ul>
    </div>
</div>
<!-- entry END -->