<?php
/**
 * キーワード検索またはタグ検索の結果を表示するページ
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Default
 * @subpackage View_Script_Page
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      var description
 * @author     akitsukada
 */
?>
<!-- entry START -->
<div class="entry">
    <div class="entryHead">
        <h2><span>「<?php echo $this->keyword ?>」の検索結果（<?php echo $this->resultCount ?>件）</span></h2>
    </div>
    <table>
        <colgroup width="28%"></colgroup>
        <colgroup width="62%"></colgroup>
        <?php foreach ($this->searchResult as $cnt => $entry): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl('page/show/id/').$entry['id'] ?>"><?php echo $entry['title'] ?></a></td>
            <td><?php echo mb_substr($entry['contents'],0,15,'UTF-8') ?>... （<?php echo date('Y年m月d日', strtotime($entry['update_date'])) ?>）</td>
        </tr>
        <?php endforeach ?>
    </table>
    <?php echo $this->paginator ?>
    <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>
</div>
<!-- entry END -->