<?php
/**
 * キーワード検索またはタグ検索の結果を表示するページ
 *
 * LICENSE: ライセンスに関する情報
 *
 * @category   Setuco
 * @package    Default
 * @subpackage View_Script_Page
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      keyword 検索に使われた文字列
 * @param      resultCount 検索結果の件数
 * @param      searchResult 検索結果を収めた配列
 * @author     akitsukada
 */
?>
<!-- entry START -->
<div class="entry">
    <div class="entryHead">
        <h2><span>「<?php echo $this->keyword ?>」の検索結果（<?php echo $this->resultCount ?>件）</span></h2>
    </div>
    <table>
        <colgroup>
            <col width="28%" />
            <col width="62%" />
        </colgroup>
        <?php foreach ($this->searchResult as $cnt => $entry): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl('page/show/id/').$entry['id'] ?>"><?php echo $entry['title'] ?></a></td>
            <td><?php echo $entry['contents'] ?>... （<?php echo $entry['update_date'] ?>）</td>
        </tr>
        <?php endforeach ?>
    </table>
</div>
<!-- entry END -->
<?php echo $this->paginator //ページャーの表示 ?>