<!-- entry START -->
<div class="entry">
    <div class="entryHead">
        <h2><span><?php echo $this->page['title'] ?></span></h2>
        <p><?php echo date('Y/m/d H:i', strtotime($this->page['update_date'])) ?></p>
    </div>
    <dl class="category">
        <dt>カテゴリー：</dt>
        <dd>
            <a href="<?php echo $this->baseUrl('page/category/id/') . $this->category['id'] ?>"><?php echo $this->category['name'] ?></a>
        </dd>
    </dl>
    <div class="entryBody">
        <?php echo $this->page['contents'] ?>
        <dl class="entryTag">
            <dt>タグ：</dt>
            <?php if (count($this->tags) > 0) : ?>
                <?php foreach ($this->tags as $cnt => $tag): ?>
                <dd><a href="<?php echo $this->baseUrl('page/tag/id/') . $tag['id'] ?>"><?php echo $tag['name'] ?></a></dd>
                <?php endforeach ?>
            <?php else: ?>
                <dd>なし</dd>
            <?php endif; ?>
        </dl>
    </div>
    <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>
</div>
<!-- entry END -->