<?php
/**
 * ページを表示するページ
 *
 * Copyright (c) 2010-2011 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * All Rights Reserved.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * @category   Setuco
 * @package    Default
 * @subpackage View_Script_Page
 * @license    http://www.opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2
 * @copyright  Copyright (c) 2010 SetucoCMS Project.(http://sourceforge.jp/projects/setucocms)
 * @link
 * @version
 * @since      File available since Release 0.1.0
 * @param      page 表示すべきページのデータ
 * @param      category ページが属するカテゴリのデータ
 * @param      tags ページにつけられたタグのデータ
 * @author     akitsukada
 */
?>

<!-- entry START -->
<div class="entry">
    <div class="entryHead">
        <h2><span><?php echo $this->escape($this->page['title']) ?></span></h2>
        <p><?php echo $this->page['update_date'] ?></p>
    </div>
    <dl class="category">
        <dt>カテゴリー：</dt>
        <dd>
            <a href="<?php echo $this->baseUrl('page/category/id/') . $this->category['id'] ?>"><?php echo $this->escape($this->category['name']) ?></a>
        </dd>
    </dl>
    <div class="entryBody">
        <?php echo $this->page['contents'] . "\n" ?>
        <dl class="entryTag">
            <dt>タグ：</dt>
            <?php if (count($this->tags) > 0): ?>
                <?php foreach ($this->tags as $cnt => $tag): ?>
                <dd><a href="<?php echo $this->baseUrl('page/tag/id/') . $tag['id'] ?>"><?php echo $this->escape($tag['name']) ?></a></dd>
                <?php endforeach ?>
            <?php else: ?>
                <dd>なし</dd>
            <?php endif; ?>
        </dl>
    </div>

    <div class="socialButton">
        <ul>
            <li class="twitter">
                <a href="https://twitter.com/share" class="twitter-share-button" data-lang="ja">ツイート</a>
            </li>
            <li class="hatena">
                <a href="http://b.hatena.ne.jp/entry/" class="hatena-bookmark-button" data-hatena-bookmark-layout="simple-balloon" title="このエントリーをはてなブックマークに追加"><img src="http://b.st-hatena.com/images/entry-button/button-only.gif" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a>
            </li>
            <li class="plusone">
                <g:plusone size="medium" data-href=""></g:plusone>
            </li>
            <li class="facebook">
                <fb:like href="" send="false" layout="button_count" show_faces="false"></fb:like>
            </li>
            <li class="line">
                <script type="text/javascript" src="http://media.line.naver.jp/js/line-button.js" ></script>
                <script type="text/javascript">
                new jp.naver.line.media.LineButton({"pc":true,"lang":"ja","type":"a"});
                </script>
            </li>
        </ul>
    </div>

    <p class="backTop"><a href="#wrapper">ページの先頭に戻る</a></p>
</div>
<!-- entry END -->
